### ISSUE TITLE
Universal Scanners become invisible in alternate modes

### ISSUE THREAD

**Issue by Samarai** [NovaSector/NovaSector#103]
## Issue Summary:
If a universal scanner is switched to the Sales Tagger or Price Tagger mode, it will become invisible. 

(also please for the love of god make the "report issue" button use this github so it's actually usable)

## Round ID:
10226

## Testmerges:
idk

## Reproduction:

1. Acquire universal scanner.
2. Press use in-hand key (Z) to open mode switch menu.
3. Note that the aforementioned modes have no sprites, but are still selectable.
4. Select, and note that the universal scanner is now invisible, but still usable.

**Comment by nikothedude** [comment]
congrats on the first issue
