### ISSUE TITLE
More chemicals for synths

### ISSUE THREAD

**Issue by delingar** [NovaSector/NovaSector#1034]
1. Make synthetics to metabolize Borer's meth (it's *unique* version so hypothetically it can be absorbed by synth)
2. Make new chemicals for synthetics as Ephedrine, Meth and so on analogues for increasing speed, stamina regenerate and so on.

**Comment by Floofies** [comment]
Hello!

This form is primarily for bug-reports. For development suggestions, please utilize the [#development-suggest](https://discord.com/channels/1171566433923239977/1188204331657334906) channel of the NovaSector Discord server such that it can be engaged with the community.
