### ISSUE TITLE
PDA Not beeping when recieving a message on it.

### ISSUE THREAD

**Issue by RikuuTheRiolu** [NovaSector/NovaSector#1064]
## Issue Summary

My PDA refuses to beep any message that is received, when someone sends me a message, I do not receive a notification on the text board or the audio ping from my PDA. What should happen is I receive a visual cue in the text board allowing me to see the message and respond back and hear the auditorial ping from the PDA.

## Reproduction:

I am unsure how to reproduce this as its only happened to me. (Rhyzal) For some reason but from my best guess on how to reproduce it.
Set your Ringtone to "Unread Message" and maybe it'll happen to you?

**Comment by GoldenAlpharex** [comment]
@RikuuTheRiolu did you try changing your ringtone to something else and seeing if it still causes issues?

**Comment by RikuuTheRiolu** [comment]
I've tried changing it to multiple things but it seems to default back to "Unread message."  no matter what i change it too.

**Comment by RikuuTheRiolu** [comment]
![Capture](https://github.com/NovaSector/NovaSector/assets/113154556/d942b729-d201-4ea5-b233-17c9369be733)

i also have this image! I'm not sure if it'll help explain the issue or not but i hope it'll help! Even if the direct messenger is open or closed it will still not show the "Reply" option in the chat if yall know what I'm saying.

**Comment by RikuuTheRiolu** [comment]
@GoldenAlpharex 
Sorry if I seem pushy about this but is there anyway I can fix this? if not, then is it possible to reset the character slot and hope it won't happen again?

**Comment by RikuuTheRiolu** [comment]
Here is also some video proof i Just nabbed (i couldnt figure out how to compress mp4's untill now. A Thousand apologies.)  

https://github.com/NovaSector/NovaSector/assets/113154556/29791f3a-5dda-490c-922d-432c1b976b12

**Comment by RikuuTheRiolu** [comment]
I found the issue, Turns out im a big goof who never cleared the cache of the BYOND client itself. A trillion apologies for the mishap everyone. Let my failure be a lesson to you all to CLEAR THE CACHE! Thank you all for the help <3

**Comment by FlufflesTheDog** [comment]
this was actually caused by having an unoccupied pAI in your pda
fixed for actually by #3238
