### ISSUE TITLE
The pipebomb recipe is broken

### ISSUE THREAD

**Issue by Krypandenej** [NovaSector/NovaSector#1263]
Reporting client version: 514.1589

## Issue Summary

The recipe for pipe bombs is broken. I tried using the standard materials, as well as some scrubber pipe.

## Round ID:
[10285](https://scrubby.melonmesa.com/round/10285)

## Testmerges:
- [[Semi-Modular]Ports over the old Food Prefs PR](https://github.com/NovaSector/NovaSector/pull/352)
- [[DNM] Temp logging fix to squelch flood logs from deathmatch](https://github.com/NovaSector/NovaSector/pull/1047)
- [Makes mystery boxes funnier by adding some of our stuff to them](https://github.com/NovaSector/NovaSector/pull/1059)
- [Light It Up! - Craftable wall-mounted torches](https://github.com/NovaSector/NovaSector/pull/1091)
- [[MODULAR] Shapeshifter Quirk](https://github.com/NovaSector/NovaSector/pull/1065)
- [Linen Plant Bags! - Adds a primitive reskin of the plant bag, makes it the default when crafted by Icewalkers](https://github.com/NovaSector/NovaSector/pull/1156)
- [Adds a stone cauldron](https://github.com/NovaSector/NovaSector/pull/1137)
- [[NON-MODULAR] Physical Age & Chronological Age](https://github.com/NovaSector/NovaSector/pull/1161)
- [Unapologetic Social Anxiety Nerfs Vol. 1 (feat. Feign Impairment)](https://github.com/NovaSector/NovaSector/pull/1239)
- [[Modular] Cryo tubes now announce on department channels when heads of staff cryo.](https://github.com/NovaSector/NovaSector/pull/1248)

## Reproduction:

Attempt to craft the Improvised Explosive with pipe harvested from the ground, lit welder and all.

**Comment by OrbisAnima** [comment]
tested it upstream, no problems

**Comment by Sadboysuss** [comment]
It was fixed upstream, still happening?
