### ISSUE TITLE
mhelp, msay and looc verb doesn't work

### ISSUE THREAD

**Issue by Iajret** [NovaSector/NovaSector#1345]
## Issue Summary
It started happening after https://github.com/NovaSector/NovaSector/pull/1292. You can still use looc by pressing L button, but not mhelp or msay. Doesn't seem to happen every time, but happens in like 90% of rounds. Yes, restart could fix it, somehow. I can't quite figure how adding additional types for input could break verbs, neither how to fix that issue without breaking OD lints. Also, i can't supply any round info since i found this bug on our downstream but Nova seemed to have that same issue.
P.S. Tested on 515.1630, 515.1633, and latest version of 514 (thats client versions)

## Round ID:
n/a

## Testmerges:
n/a

## Reproduction:
- Enter server
- press mentorhelp
- nothing happens
- try other verbs (e.g. looc)
- notice they don't work too

**Comment by Iajret** [comment]
Removing `|null` does indeed fixed it. I'm not even sure if it is needed for OpenDream to work or not.

**Comment by codyman765** [comment]
Am also having this bug as well, though it is very consistent with every round.
