### ISSUE TITLE
Mentorhelp Broken

### ISSUE THREAD

**Issue by TripleShades** [NovaSector/NovaSector#1471]
Reporting client version: 515.1633

## Issue Summary
The input box to open the mhelp does not pop up when pressing the Mentorhelp link in the statpanel, nor when using the bar command Mentorhelp.

## Round ID:
[10374](https://scrubby.melonmesa.com/round/10374)

## Testmerges:
- [[DNM] Temp logging fix to squelch flood logs from deathmatch](https://github.com/NovaSector/NovaSector/pull/1047)
- [Adds a stone cauldron](https://github.com/NovaSector/NovaSector/pull/1137)
- [Unapologetic Ethereal Electricitycreep Buff PR Vol. 1](https://github.com/NovaSector/NovaSector/pull/1179)
- [[MODULAR] Shameless Hypospray Buffs & Polish](https://github.com/NovaSector/NovaSector/pull/1283)
- [private PDA messaging (sexting) not viewable by ghosts.](https://github.com/NovaSector/NovaSector/pull/1329)
- [[MODULAR] Adds an entirely new map to Nova's roster: Ouroboros!](https://github.com/NovaSector/NovaSector/pull/773)
- [[MODULAR] Mag-fed Deployable Turrets + Target Designator.](https://github.com/NovaSector/NovaSector/pull/1108)

## Reproduction:
See summary.

**Comment by Iajret** [comment]
https://github.com/NovaSector/NovaSector/issues/1345
