### ISSUE TITLE
stock market broken electric boogaloo 2

### ISSUE THREAD

**Issue by annikaRU** [NovaSector/NovaSector#1492]
Reporting client version: 514.1589

## Issue Summary

Send a cube inside the shuttle (stock block), it will show up as nothing was ever sent 

## Round ID:
[10382](https://scrubby.melonmesa.com/round/10382)

## Testmerges:
- [[DNM] Temp logging fix to squelch flood logs from deathmatch](https://github.com/NovaSector/NovaSector/pull/1047)
- [Adds a stone cauldron](https://github.com/NovaSector/NovaSector/pull/1137)
- [Unapologetic Ethereal Electricitycreep Buff PR Vol. 1](https://github.com/NovaSector/NovaSector/pull/1179)
- [[MODULAR] Shameless Hypospray Buffs & Polish](https://github.com/NovaSector/NovaSector/pull/1283)
- [private PDA messaging (sexting) not viewable by ghosts.](https://github.com/NovaSector/NovaSector/pull/1329)
- [[MODULAR] Adds an entirely new map to Nova's roster: Ouroboros!](https://github.com/NovaSector/NovaSector/pull/773)
- [[MODULAR] Mag-fed Deployable Turrets + Target Designator.](https://github.com/NovaSector/NovaSector/pull/1108)
- [I See Clearly Now: customizable echolocation quirk](https://github.com/NovaSector/NovaSector/pull/525)
- [Disables the Drifting Contractor random event in favor of using dynamic only to spawn them](https://github.com/NovaSector/NovaSector/pull/1479)

## Reproduction:

Create a stock block inside of the stock market put it onto the shuttle and send the shuttle, will show up as nothing ever was sent. Now create a stock block and add your ID to sell it for 50% you will get the 50% split but nothing will be added to cargo's budget, and the same result will happen nothing will show as something was sold

**Comment by annikaRU** [comment]
After investigating it further, I have discovered export value is listed as 0, that does not explain why selling it at 50% will still give you half the blocks value however the way to do market now is to sell blocks at an extremely high value on a personal account and transfer it to the budget card as a work around

**Comment by Namwty** [comment]
Upstream issue I believe, there is a PR on TG's side that aims to fix this I think.

**Comment by annikaRU** [comment]
Closing due to it being likely fixed or was a single time error (I havent encountered it)
