### ISSUE TITLE
Shoulder Holster cannot hold ammo boxes (Maybe not a bug?)

### ISSUE THREAD

**Issue by Samarai** [NovaSector/NovaSector#163]
Reporting client version: 514.1589

## Issue Summary:
The leather shoulder holster is seemingly intended, based on the list of allowed items shown if you examine it twice, to be capable of holding ammo boxes, like those purchasable in company imports for a few ammo types. (ammo boxes are not to be confused with cardboard boxes that have shells in them, like the bartender starts with; those are still storage items, and as such are subject to the same inventory-nesting rules as any storage item) However, none will fit. Additionally, the allowed items list ingame shows the ammo box entry as _an ammo box (null_reference_exception)_, which may be the cause of this issue.

## Round ID:
[10252](https://scrubby.melonmesa.com/round/10252)

## Testmerges:
- [[Semi-modular] Gives Xeno-hybrids some xeno-organs in trade for high temperature weakness](https://github.com/NovaSector/NovaSector/pull/91)
- [Colony lathe fixes, changes, and some small features | WIND POWER IS THE FUTURE](https://github.com/NovaSector/NovaSector/pull/94)
- [Antag optin ](https://github.com/NovaSector/NovaSector/pull/121)
- [[TM ONLY] Early mirror- fix TextArea lag](https://github.com/NovaSector/NovaSector/pull/128)
- [Period Era Re-Enactment: Basic autopunctuation](https://github.com/NovaSector/NovaSector/pull/84)

## Reproduction:

1. Acquire shoulder holster, attach to your belt or suit storage slot (which can now be done with almost any suit item yay) for convenience.
2. Get an ammo box that is normal-sized or smaller.
3. Attempt to put it in the holster, and fail.

**Comment by Samarai** [comment]
Added "maybe not a bug" because looking in the code, it seems like the basic shoulder holster isn't intended to hold ammo boxes because that is not in its allowed list, meanwhile the detective holster does have a line in its list mentioning a few ammo boxes (including speedloaders)
This only makes ammo boxes being shown ingame when shoulder holsters are double-examined even more puzzling; I think there's definitely a bug of some sort happening with this, just not the one I reported. And I'm not sure how basic leather holsters are capable of holding magazines since there are no ammo boxes in the allowed list, and magazines count as ammo boxes? I think? I don't know, I'm not a coder and this seems messy in general.

**Comment by OrionTheFox** [comment]
Did some digging. The culprit item, `/obj/item/ammo_box/magazine` is missing a unique name, due to being a base type

Source:
`code\modules\projectiles\boxes_magazines\_box_magazine.dm`
```nix
/obj/item/ammo_box
name = "ammo box (null_reference_exception)"
```

Interestingly, the item is never uniquely defined on TG; it's immediately referred to in-code as any of its subtypes. This would technically qualify as an Upstream issue since their syndicate holster has the same issue on it, as the **only** instance of the base `/obj/item/ammo_box/magazine` being used on TG.

**Comment by Samarai** [comment]
Closing this issue report then, that bug is upstream and doesn't affect gameplay, and I'm too lazy to go there to report it.
