### ISSUE TITLE
Echolocation bug where everyone becomes the same person

### ISSUE THREAD

**Issue by SpaceShadok** [NovaSector/NovaSector#1664]
## Issue Summary

Sometimes the echolocation quirk picks one character and displays everyone as them for the rest of the round.
I've tried relogging, using the start/stop echolocation "spell", clearing the cache, dying and being revived, respawning, and switching to another character with a different type of echolocation. Nothing fixed it.

![i hate it](https://github.com/NovaSector/NovaSector/assets/165171992/b7f1a081-6dad-40c2-8855-c57bcd000fca)
The outlines never change, even if the "original" character changes their outfit or appearance after the bug happens. Sprite size and orientation are still displayed correctly though.

Interestingly this screenshot happened when the one character got fultoned. That resulted in everyone keeping the balloon, and their outline appearing above their actual position, which makes it hard to not hit yourself or others on accident.

## Round ID:
[10452](https://scrubby.melonmesa.com/round/10452)

**Comment by SpaceShadok** [comment]
The bug happens consistently (but not exclusively) when someone gets fultonned in view, so that's a way to reproduce it.

**Comment by Greenjoe12345** [comment]
This happened for me in the ghost cafe today, it happened randomly, out of nowhere.
![image](https://github.com/NovaSector/NovaSector/assets/33647525/a7a6a3f0-36d1-40f2-92b0-73fc668d4203)

**Comment by Sadboysuss** [comment]
https://github.com/tgstation/tgstation/pull/86604
