### ISSUE TITLE
Borgs unlockable by assistants

### ISSUE THREAD

**Issue by wivernshy** [NovaSector/NovaSector#1719]
Reporting client version: 515.1633

## Issue Summary
For some reason, assistants (and presumably other jobs, haven't yet tested) have access to unlock a borgs panel. Normally only roboticists, the RD, and the borgs themself should be able to do this

## Round ID:
[10474](https://scrubby.melonmesa.com/round/10474)

## Testmerges:
- [Unapologetic Ethereal Electricitycreep Buff PR Vol. 1](https://github.com/NovaSector/NovaSector/pull/1179)
- [[MODULAR] Adds an entirely new map to Nova's roster: Ouroboros!](https://github.com/NovaSector/NovaSector/pull/773)
- [[MODULAR] Mag-fed Deployable Turrets + Target Designator.](https://github.com/NovaSector/NovaSector/pull/1108)
- [I See Clearly Now: customizable echolocation quirk](https://github.com/NovaSector/NovaSector/pull/525)
- [[MODULAR] Adds a dice roll emote](https://github.com/NovaSector/NovaSector/pull/1556)
- [Unapologetic Teshari Buffs Vol. 1](https://github.com/NovaSector/NovaSector/pull/1442)
- [Adds more fake Syndicate clothing to the loadout list, fixes and balances the existing ones](https://github.com/NovaSector/NovaSector/pull/1560)
- [High heel sounds for some high heel shoes](https://github.com/NovaSector/NovaSector/pull/1639)
- [[PORT] [SEMI-MODULAR] [JANK] Ports the lovely Character Directory which was ported from Coyote Bayou](https://github.com/NovaSector/NovaSector/pull/183)
- [Re-enables borg resizing for Tall/Wide with more aggressive limits](https://github.com/NovaSector/NovaSector/pull/1687)
- [[MIRROR] Converts some TGUI to typescript](https://github.com/NovaSector/NovaSector/pull/1707)
- [Adds a fennec pet](https://github.com/NovaSector/NovaSector/pull/1695)
- [Adding Craftable Tribal Chisel. Set Tribal Tool Material Type to Bone.](https://github.com/NovaSector/NovaSector/pull/1708)

## Reproduction:
Borgs are free, you can just walk up and take them (by slapping your PDA on their sprite, and watching it unlock)

**Comment by Sadboysuss** [comment]
Doesn't seem to be an issue anymore, comment here if you still see it happening.
This is marked for cleanup and will be auto-closed in 7 days
