### ISSUE TITLE
Icebox not dropping ores again

### ISSUE THREAD

**Issue by Thlumyn** [NovaSector/NovaSector#1746]
Reporting client version: 515.1633

## Issue Summary

Icebox is having that issue again where you break a rock that should have ore, and more often than not, no ore drops. Not sure if this is an upstream issue or nova issue

## Round ID:
[10485](https://scrubby.melonmesa.com/round/10485)

## Testmerges:
- [Unapologetic Ethereal Electricitycreep Buff PR Vol. 1](https://github.com/NovaSector/NovaSector/pull/1179)
- [[MODULAR] Adds an entirely new map to Nova's roster: Ouroboros!](https://github.com/NovaSector/NovaSector/pull/773)
- [[MODULAR] Mag-fed Deployable Turrets + Target Designator.](https://github.com/NovaSector/NovaSector/pull/1108)
- [[MODULAR] Adds a dice roll emote](https://github.com/NovaSector/NovaSector/pull/1556)
- [Unapologetic Teshari Buffs Vol. 1](https://github.com/NovaSector/NovaSector/pull/1442)
- [Adds more fake Syndicate clothing to the loadout list, fixes and balances the existing ones](https://github.com/NovaSector/NovaSector/pull/1560)
- [[PORT] [SEMI-MODULAR] [JANK] Ports the lovely Character Directory which was ported from Coyote Bayou](https://github.com/NovaSector/NovaSector/pull/183)
- [Re-enables borg resizing for Tall/Wide with more aggressive limits](https://github.com/NovaSector/NovaSector/pull/1687)

## Reproduction:

Mining, on ice box. Specifically, I was testing this was a plasma cutter and no character skill in mining

**Comment by Drayco84** [comment]
I think the minimum ore amounts generated in the rock are less than 1 piece of ore for the map, especially around the base. With low mining, the drop system rounds down while at high mining, the system adds enough of a yield bonus to generate 1 piece of ore.
