### ISSUE TITLE
Nuke Core objective doesn't provide kit to sleepers

### ISSUE THREAD

**Issue by Samarai** [NovaSector/NovaSector#1820]
## Issue Summary:
The nuke core extraction objective given out to Syndicate Sleeper Agent antags is intended to give them an extraction kit containing the storage item for the core, a fine-tip screwdriver (required), and a paper with the instructions on how to extract the core. This does not occur, and makes the objective impossible to complete without admin intervention.

## Reproduction:

1. Get the objective in question as a Sleeper agent.
2. Lament lack of required tools (and enclosed instruction booklet) for completing this objective.

**Comment by Sadboysuss** [comment]
Doesn't seem to be an issue anymore, comment here if you still see it happening.
This is marked for cleanup and will be auto-closed in 7 days
