### ISSUE TITLE
Pride doesn't space you

### ISSUE THREAD

**Issue by TripleShades** [NovaSector/NovaSector#1821]
Reporting client version: 515.1633

## Issue Summary
See title.

## Round ID:
10519

## Testmerges:
- [[MODULAR] Adds an entirely new map to Nova's roster: Ouroboros!](https://github.com/NovaSector/NovaSector/pull/773)
- [[MODULAR] Mag-fed Deployable Turrets + Target Designator.](https://github.com/NovaSector/NovaSector/pull/1108)
- [[MODULAR] Adds a dice roll emote](https://github.com/NovaSector/NovaSector/pull/1556)
- [[PORT] [SEMI-MODULAR] [JANK] Ports the lovely Character Directory which was ported from Coyote Bayou](https://github.com/NovaSector/NovaSector/pull/183)
- [Re-enables borg resizing for Tall/Wide with more aggressive limits](https://github.com/NovaSector/NovaSector/pull/1687)
- [[Semi-Modular] HMS Buffs](https://github.com/NovaSector/NovaSector/pull/1742)
- [Smooth the alcohol impairment curve because a bottle of vodka should last more than 5 minutes](https://github.com/NovaSector/NovaSector/pull/1793)

## Reproduction:
Use Pride (The Lavaland Ruin named Pride, it has a Magic Mirror.)
Pick Synthetic Humanoid.
Fuck around with the other options but NOT race.
Press the X when done.
Discover that you're now, for free and clear, a robot man. Yipee! (Become disappointed because you wanted to get lost in space.)

**Comment by Sadboysuss** [comment]
What? Why would it space you?

**Comment by TripleShades** [comment]
> What? Why would it space you?

In the code, it's meant to space you, and I dont know if Skyrat put in an override or if the code just broke.
It's the downside for being able to basically pick any species, including halloween and antag.

**Comment by TripleShades** [comment]
Will be closed by https://github.com/tgstation/tgstation/pull/86079

**Comment by TripleShades** [comment]
https://github.com/NovaSector/NovaSector/pull/4353 ports the above
