### ISSUE TITLE
Temp flavor text span has lost its bolding

### ISSUE THREAD

**Issue by nikothedude** [NovaSector/NovaSector#1848]
Reporting client version: 515.1635

## Issue Summary

Title.

![image](https://github.com/NovaSector/NovaSector/assets/59709059/3c49cd23-8708-44e2-9738-c08426b8463e)

Its supposed to be bold...

![image](https://github.com/NovaSector/NovaSector/assets/59709059/a680ed88-60f5-409a-bb23-8a2838d69f53)

But its not.

## Round ID:
[10533](https://scrubby.melonmesa.com/round/10533)

## Testmerges:
- [[MODULAR] Adds an entirely new map to Nova's roster: Ouroboros!](https://github.com/NovaSector/NovaSector/pull/773)
- [[MODULAR] Mag-fed Deployable Turrets + Target Designator.](https://github.com/NovaSector/NovaSector/pull/1108)
- [[MODULAR] Adds a dice roll emote](https://github.com/NovaSector/NovaSector/pull/1556)
- [[PORT] [SEMI-MODULAR] [JANK] Ports the lovely Character Directory which was ported from Coyote Bayou](https://github.com/NovaSector/NovaSector/pull/183)
- [Re-enables borg resizing for Tall/Wide with more aggressive limits](https://github.com/NovaSector/NovaSector/pull/1687)
- [[Semi-Modular] HMS Buffs](https://github.com/NovaSector/NovaSector/pull/1742)
- [Smooth the alcohol impairment curve because a bottle of vodka should last more than 5 minutes](https://github.com/NovaSector/NovaSector/pull/1793)
- [Fix multi-cell charger and convert to new grid power consumption](https://github.com/NovaSector/NovaSector/pull/1825)
- [[Moduler] Adjusts the limits before APC's ARC](https://github.com/NovaSector/NovaSector/pull/1824)

## Reproduction:

just set temp ftext you goober

**Comment by lessthnthree** [comment]
Not a bug. Bolding of the field was removed in https://github.com/NovaSector/NovaSector/pull/1616 as part of the reorg/restyle.

**Comment by nikothedude** [comment]
but yes, not a bug

**Comment by nikothedude** [comment]
how do i close issues

**Comment by lessthnthree** [comment]
Cleaning up the text to TG consistent standards, whole blocks of text are not bolded. That is reserved for examine hints.

The purple is meant to catch the eye.

![image](https://github.com/NovaSector/NovaSector/assets/83487515/90f9aaeb-7bcb-4f92-bff8-452c15879cf3)

**Comment by nikothedude** [comment]
the "They look different than usual" was also bolded to mark it as the prefix, the thing hat never changes. It should probably have some span that differentiates it from the actual text

**Comment by lessthnthree** [comment]
> the "They look different than usual" was also bolded to mark it as the prefix, the thing hat never changes. It should probably have some span that differentiates it from the actual text

Yeah I'm not opposed to your request to increase visibility. I will make an adjustment.
