### ISSUE TITLE
AI missing from latejoin menu

### ISSUE THREAD

**Issue by wivernshy** [NovaSector/NovaSector#1861]
Reporting client version: 515.1633

## Issue Summary
Usually a job will show on the menu whether it's filled or not, but AI was outright missing from the menu during this round instead of being greyed out, since it's filled.
![image](https://github.com/NovaSector/NovaSector/assets/46330016/1825fd34-34d8-46a2-801c-ed5e787def92)

## Round ID:
[10541](https://scrubby.melonmesa.com/round/10541)

## Testmerges:
- [[MODULAR] Adds an entirely new map to Nova's roster: Ouroboros!](https://github.com/NovaSector/NovaSector/pull/773)
- [[MODULAR] Mag-fed Deployable Turrets + Target Designator.](https://github.com/NovaSector/NovaSector/pull/1108)
- [[MODULAR] Adds a dice roll emote](https://github.com/NovaSector/NovaSector/pull/1556)
- [[PORT] [SEMI-MODULAR] [JANK] Ports the lovely Character Directory which was ported from Coyote Bayou](https://github.com/NovaSector/NovaSector/pull/183)
- [Re-enables borg resizing for Tall/Wide with more aggressive limits](https://github.com/NovaSector/NovaSector/pull/1687)
- [Smooth the alcohol impairment curve because a bottle of vodka should last more than 5 minutes](https://github.com/NovaSector/NovaSector/pull/1793)
- [Fix multi-cell charger and convert to new grid power consumption](https://github.com/NovaSector/NovaSector/pull/1825)
- [[Moduler] Adjusts the limits before APC's ARC](https://github.com/NovaSector/NovaSector/pull/1824)
- [[MODULAR] Documents akula features in the perks window](https://github.com/NovaSector/NovaSector/pull/1826)
- [[Non-modular] Security bots now check if you're allowed to carry that gun by default](https://github.com/NovaSector/NovaSector/pull/1832)
- [[MIRROR] Revert "Pre-516 tgui prep (#82473)"](https://github.com/NovaSector/NovaSector/pull/1847)

**Comment by Sadboysuss** [comment]
Doesn't seem to be an issue anymore, comment here if you still see it happening.
This is marked for cleanup and will be auto-closed in 7 days
