### ISSUE TITLE
mining drone upgrades missing (possibly others)

### ISSUE THREAD

**Issue by RatFromTheJungle** [NovaSector/NovaSector#1942]
## Issue Summary

The mining vendor is missing mining drone upgrades, likely other things that haven't been noticed yet.

## Testmerges:
#773 
#1108 
#1556 
#183 
#1687 
#1793
#1858 
#1925
## Reproduction:

go ingame expecting to see:
![image](https://github.com/NovaSector/NovaSector/assets/62520989/acd5bb78-16a3-4ed8-9c3a-bea0dd6244fd)
instead see: 
![image](https://github.com/NovaSector/NovaSector/assets/62520989/3b78c535-f4be-471a-b612-c77e868c8e14)
(no shield upgrade)

**Comment by codyman765** [comment]
Noticed the same thing in #1753 It looks like the remote made it in, but the bot is unable to fire the rockets aswell. seems like a fair bit of the minebot overhaul got jumbled up somewhere.

**Comment by RatFromTheJungle** [comment]
fixed now
