### ISSUE TITLE
bluespace techs lag upon spawn. 

### ISSUE THREAD

**Issue by MaSvedish** [NovaSector/NovaSector#1952]
Reporting client version: 515.1634

## Issue Summary
bluespace techs cause a rendering lag everyone within screen distance of them because you drop half of your bag of materials. 

## Round ID:
[10578](https://scrubby.melonmesa.com/round/10578)

## Testmerges:
- [[MODULAR] Adds an entirely new map to Nova's roster: Ouroboros!](https://github.com/NovaSector/NovaSector/pull/773)
- [[MODULAR] Mag-fed Deployable Turrets + Target Designator.](https://github.com/NovaSector/NovaSector/pull/1108)
- [[MODULAR] Adds a dice roll emote](https://github.com/NovaSector/NovaSector/pull/1556)
- [[PORT] [SEMI-MODULAR] [JANK] Ports the lovely Character Directory which was ported from Coyote Bayou](https://github.com/NovaSector/NovaSector/pull/183)
- [Re-enables borg resizing for Tall/Wide with more aggressive limits](https://github.com/NovaSector/NovaSector/pull/1687)
- [Smooth the alcohol impairment curve because a bottle of vodka should last more than 5 minutes](https://github.com/NovaSector/NovaSector/pull/1793)
- [[Semi-Modular]  Adds TGUI Chat Prefix Colors for various Faction Radios + Fixes Solfed Radios](https://github.com/NovaSector/NovaSector/pull/1858)
- [Revert "[MIRROR] General maintenance for chem master"](https://github.com/NovaSector/NovaSector/pull/1925)

## Reproduction:
spawn as bluespace tech.

**Comment by lessthnthree** [comment]
Upstream bug.

**Comment by FlufflesTheDog** [comment]
Should be fixed by #2227
