### ISSUE TITLE
"Air canister" Sprite Error

### ISSUE THREAD

**Issue by Knightscholar** [NovaSector/NovaSector#206]
Reporting client version: 514.1589

## Issue Summary

The sprite for the Air canisters is incorrect, and seems to be some sort of beam. It otherwise functions exactly as expected.

## Round ID:
[10267](https://scrubby.melonmesa.com/round/10267)

## Testmerges:
- [[Semi-modular] Gives Xeno-hybrids some xeno-organs in trade for high temperature weakness](https://github.com/NovaSector/NovaSector/pull/91)
- [Colony lathe fixes, changes, and some small features | WIND POWER IS THE FUTURE](https://github.com/NovaSector/NovaSector/pull/94)
- [Antag optin ](https://github.com/NovaSector/NovaSector/pull/121)
- [Period Era Re-Enactment: Basic autopunctuation](https://github.com/NovaSector/NovaSector/pull/84)
- [Adds fancy masquerade masks](https://github.com/NovaSector/NovaSector/pull/180)

## Reproduction:

The canisters labeled as Air spawn with an incorrect sprite from shiftstart. Labeling any can as Air causes the incorrect sprite to show up also. The can functions as normal, and does not revert to the correct sprite at any point. If an air tank is attached to the canister, the spite updates to feature the tank on it, but it remains incorrect. Additionally, the sprites for tank port, the battery, and the shielding show up correctly, overlaid on top of the incorrect sprite.

**Comment by Floofies** [comment]
@vinylspiders 
This does not seem to be reproducible anymore. If it was ever an issue then I assume it was caused by their local byond cache being corrupted.
