### ISSUE TITLE
Resetting a shrunk borg causes a growth spurt

### ISSUE THREAD

**Issue by wivernshy** [NovaSector/NovaSector#2080]
Reporting client version: 515.1633

## Issue Summary
Resetting a borg with a shrinker module installed will make their sprite larger, as if they had the enlarge module instead.  Reinstalling the shrinker module afterwards only return them to normal/default size.

## Round ID:
[10631](https://scrubby.melonmesa.com/round/10631)

## Testmerges:
- [[MODULAR] Adds a dice roll emote](https://github.com/NovaSector/NovaSector/pull/1556)
- [[PORT] [SEMI-MODULAR] [JANK] Ports the lovely Character Directory which was ported from Coyote Bayou](https://github.com/NovaSector/NovaSector/pull/183)
- [Nuts](https://github.com/NovaSector/NovaSector/pull/1795)
- [the black market thrives in its newfound popularity, harboring more merchants and wares](https://github.com/NovaSector/NovaSector/pull/1366)
- [Ooey Gooey Slimegirl Buffs Vol. 1](https://github.com/NovaSector/NovaSector/pull/1661)
- [[SEMI-MODULAR] Allows users to customize fragile's brute/burn mods, adds physiology damage mult to health analyzers](https://github.com/NovaSector/NovaSector/pull/1800)
- [Removes Syndicate Bombs (the gargantuan one) from Syndicate Uplink.](https://github.com/NovaSector/NovaSector/pull/2046)
- [Tesla coil input multiplier balance](https://github.com/NovaSector/NovaSector/pull/2038)
- [New Ashwalker base camp - "The Ash Fortress"!](https://github.com/NovaSector/NovaSector/pull/2012)
- [Adds the Deep Space deathmatch map](https://github.com/NovaSector/NovaSector/pull/1999)
- [[MODULAR] Drill Implant](https://github.com/NovaSector/NovaSector/pull/1997)

## Reproduction:
1) Be a borg with shrinker
2) get reset, choose a new model
3) congrats, you are big for free

**Comment by Sadboysuss** [comment]
Doesn't seem to be an issue anymore, comment here if you still see it happening.
This is marked for cleanup and will be auto-closed in 7 days
