### ISSUE TITLE
[Likely Upstream] Alt-clicking on unseen turfs allows viewing (and in some cases, interacting with) things through walls

### ISSUE THREAD

**Issue by Samarai** [NovaSector/NovaSector#2105]
Reporting client version: 514.1589

## Issue Summary:
A recent upstream PR changed how alt-clicking on a turf in order to look through a pile of items works, making it into a TGUI window that _doesn't_ freeze the game upon opening if you're looking at a whole pile of garbage; this is also useful for interacting with floors underneath tables and whatnot. The issue is that this does not check for if you can actually see the floors in question, and this allows you to examine things you otherwise wouldn't on the other side of walls, even without mesons, and even interact with them if it's a ranged interaction: I.E, talking to someone through walls with the telepathy quirk. (which is also possible with thermals, but I think that's somewhat intended or at least a happy accident, since you can actually see and examine the person's sprite with thermals)

## Round ID:
[10645](https://scrubby.melonmesa.com/round/10645)

## Testmerges:
- [[MODULAR] Adds a dice roll emote](https://github.com/NovaSector/NovaSector/pull/1556)
- [[PORT] [SEMI-MODULAR] [JANK] Ports the lovely Character Directory which was ported from Coyote Bayou](https://github.com/NovaSector/NovaSector/pull/183)
- [Nuts](https://github.com/NovaSector/NovaSector/pull/1795)
- [the black market thrives in its newfound popularity, harboring more merchants and wares](https://github.com/NovaSector/NovaSector/pull/1366)
- [Ooey Gooey Slimegirl Buffs Vol. 1](https://github.com/NovaSector/NovaSector/pull/1661)
- [[SEMI-MODULAR] Allows users to customize fragile's brute/burn mods, adds physiology damage mult to health analyzers](https://github.com/NovaSector/NovaSector/pull/1800)
- [Tesla coil input multiplier balance](https://github.com/NovaSector/NovaSector/pull/2038)
- [New Ashwalker base camp - "The Ash Fortress"!](https://github.com/NovaSector/NovaSector/pull/2012)
- [Adds the Deep Space deathmatch map](https://github.com/NovaSector/NovaSector/pull/1999)
- [[MODULAR] Drill Implant](https://github.com/NovaSector/NovaSector/pull/1997)
- [Dynamic Changes](https://github.com/NovaSector/NovaSector/pull/2059)

## Reproduction:

1. Alt click on a black tile on the other side of a wall you can't see through, ideally one with items on it.
2. Shift click items in the list and note that you can examine these unseen items.

**Comment by Iamgoofball** [comment]
Upstream issue, we're working on a fix
