### ISSUE TITLE
Deathmatch map bug - Ragin' mage

### ISSUE THREAD

**Issue by FieryTech** [NovaSector/NovaSector#2119]
Reporting client version: 514.1589

## Issue Summary

When, in a deathmatch session on the Ragin' mage map, you use the necromancer loadout with the blink ability, you can teleport outside of the map and inside the game world by, first, teleporting into space, and then, blinking when you are hugging the border of the deathmatch map. Technically could allow ghosts to access space ruins. The DM map timeout correctly reset the characters.

![Capture d'écran 2024-04-21 205803](https://github.com/NovaSector/NovaSector/assets/26222998/b777d430-a8f6-4085-8119-d3a18a984360)

## Round ID:
[10650](https://scrubby.melonmesa.com/round/10650)

## Testmerges:
- [[MODULAR] Adds a dice roll emote](https://github.com/NovaSector/NovaSector/pull/1556)
- [[PORT] [SEMI-MODULAR] [JANK] Ports the lovely Character Directory which was ported from Coyote Bayou](https://github.com/NovaSector/NovaSector/pull/183)
- [the black market thrives in its newfound popularity, harboring more merchants and wares](https://github.com/NovaSector/NovaSector/pull/1366)
- [Ooey Gooey Slimegirl Buffs Vol. 1](https://github.com/NovaSector/NovaSector/pull/1661)
- [[SEMI-MODULAR] Allows users to customize fragile's brute/burn mods, adds physiology damage mult to health analyzers](https://github.com/NovaSector/NovaSector/pull/1800)
- [New Ashwalker base camp - "The Ash Fortress"!](https://github.com/NovaSector/NovaSector/pull/2012)
- [Adds the Deep Space deathmatch map](https://github.com/NovaSector/NovaSector/pull/1999)
- [[MODULAR] Drill Implant](https://github.com/NovaSector/NovaSector/pull/1997)
- [Dynamic Changes](https://github.com/NovaSector/NovaSector/pull/2059)

## Reproduction:

- Open a deathmatch lobby on the Ragin' mage map.
- Take the necromancer loadout for your deathmatch character.
- Blink into space around the mage's ship.
- Blink while hugging the border of the deathmatch map.

**Comment by Sadboysuss** [comment]
Doesn't seem to be an issue anymore, comment here if you still see it happening.
This is marked for cleanup and will be auto-closed in 7 days
