### ISSUE TITLE
Supply Pods from the pod crash event cannot be removed

### ISSUE THREAD

**Issue by OrionTheFox** [NovaSector/NovaSector#213]
Reporting client version: 515.1623

## Issue Summary
Supply Pods from the random event cannot be removed

## Round ID:
[10271](https://scrubby.melonmesa.com/round/10271)

## Testmerges:
- [[Semi-modular] Gives Xeno-hybrids some xeno-organs in trade for high temperature weakness](https://github.com/NovaSector/NovaSector/pull/91)
- [Antag optin ](https://github.com/NovaSector/NovaSector/pull/121)
- [Period Era Re-Enactment: Basic autopunctuation](https://github.com/NovaSector/NovaSector/pull/84)
- [[PORT] [MODULAR] [100% FREE LAG] Chat Colors](https://github.com/NovaSector/NovaSector/pull/157)
- [Kahraman, after collecting dust for 100 years, finally has its own content, hear ye guncargo naysayers and weep](https://github.com/NovaSector/NovaSector/pull/98)
- [Expands the rapid construction fabricator's appliances to be more than four (4) things!](https://github.com/NovaSector/NovaSector/pull/130)

## Reproduction:
Have a cargo pod crash
Attempt to Unbolt/Weld it to dismantle it

Previously, this would unbolt it or cut it down into metal. Now, nothing happens.

![image](https://github.com/NovaSector/NovaSector/assets/76465278/2917dddf-15c1-45f1-8172-5e8334beb63a)
![image](https://github.com/NovaSector/NovaSector/assets/76465278/ad86651d-a74e-4606-a3ed-9750fe8df2c1)

(While holding a wrench this prompt appears, but it doesn't actually work)
![image](https://github.com/NovaSector/NovaSector/assets/76465278/c977bd33-8a1c-4eab-91ab-976eb1d4c204)

**Comment by Thlumyn** [comment]
This looks like an upstream issue, I'll try to submit a fix to tg.

**Comment by Thlumyn** [comment]
Should be addressed here: https://github.com/tgstation/tgstation/pull/80759

**Comment by Thlumyn** [comment]
When I tried it locally, left mouse button with a lit welder deconstructed the supply pod

**Comment by OrionTheFox** [comment]
> When I tried it locally, left mouse button with a lit welder deconstructed the supply pod

I wonder if the location it landed on was invalid/in a wall, or if it never ""landed"" fully?
