### ISSUE TITLE
Quick equip when all slots are full

### ISSUE THREAD

**Issue by FieryTech** [NovaSector/NovaSector#2133]
Reporting client version: 514.1589

## Issue Summary

Quick equip (Keybind E by default) when all storage slots on you are full make your drop the item you have in hand after the indicator "You are unable to equip that!" proc. That has been reported as a bug as you character wouldn't drop the item in your hands if your storage slots were full in the past.

![Capture d'écran 2024-04-22 225854](https://github.com/NovaSector/NovaSector/assets/26222998/dee76646-db8a-4937-a81d-a49959131de8)
![Capture d'écran 2024-04-22 225906](https://github.com/NovaSector/NovaSector/assets/26222998/193f46d6-7ce8-43b2-a4e5-38da39e5e503)
![Capture d'écran 2024-04-22 225914](https://github.com/NovaSector/NovaSector/assets/26222998/03618e1c-d4ec-4155-822e-823104fa0f14)

## Round ID:
[10658](https://scrubby.melonmesa.com/round/10658)

## Testmerges:
- [[MODULAR] Adds a dice roll emote](https://github.com/NovaSector/NovaSector/pull/1556)
- [[PORT] [SEMI-MODULAR] [JANK] Ports the lovely Character Directory which was ported from Coyote Bayou](https://github.com/NovaSector/NovaSector/pull/183)
- [the black market thrives in its newfound popularity, harboring more merchants and wares](https://github.com/NovaSector/NovaSector/pull/1366)
- [Ooey Gooey Slimegirl Buffs Vol. 1](https://github.com/NovaSector/NovaSector/pull/1661)
- [[SEMI-MODULAR] Allows users to customize fragile's brute/burn mods, adds physiology damage mult to health analyzers](https://github.com/NovaSector/NovaSector/pull/1800)
- [Adds the Deep Space deathmatch map](https://github.com/NovaSector/NovaSector/pull/1999)
- [Dynamic Changes](https://github.com/NovaSector/NovaSector/pull/2059)
- [Tweaks to the Interlink disposal access/room](https://github.com/NovaSector/NovaSector/pull/2079)
- [trims down akula language description](https://github.com/NovaSector/NovaSector/pull/2101)
- [[MIRROR] [READY] the unfuckening of clothing rendering](https://github.com/NovaSector/NovaSector/pull/2127)

## Reproduction:

- Fill your bag with various items until it is full.
- Fill your pockets until they are full.
- Take an item in your hand and press your quick equip hotkey.
- The item drop on the floor after a "You are unable to equip that!" message.

**Comment by Samf3232** [comment]
You are a saint

**Comment by FlufflesTheDog** [comment]
Fixed by #2170
