### ISSUE TITLE
cant unwrench racks anymore

### ISSUE THREAD

**Issue by MaineTheMan** [NovaSector/NovaSector#2143]
## Issue Summary
try to unwrench/decon a rack, you cant without breaking it

## Testmerges: merged:
[#1556: '[MODULAR] Adds a dice roll emote' by nikothedude at commit d7010f36b4](https://github.com/NovaSector/NovaSector/pull/1556)
[#183: '[PORT] [SEMI-MODULAR] [JANK] Ports the lovely Character Directory which was ported from Coyote Bayou' by W4rd3nn at commit 9c9ded6c14](https://github.com/NovaSector/NovaSector/pull/183)
[#1366: 'the black market thrives in its newfound popularity, harboring more merchants and wares' by honkpocket at commit b816d5829f](https://github.com/NovaSector/NovaSector/pull/1366)
[#1661: 'Ooey Gooey Slimegirl Buffs Vol. 1' by Nerev4r at commit 56056b2376](https://github.com/NovaSector/NovaSector/pull/1661)
[#1800: '[SEMI-MODULAR] Allows users to customize fragile's brute/burn mods, adds physiology damage mult to health analyzers' by nikothedude at commit d1c50e0110](https://github.com/NovaSector/NovaSector/pull/1800)
[#1999: 'Adds the Deep Space deathmatch map' by honkpocket at commit ab821ba91a](https://github.com/NovaSector/NovaSector/pull/1999)
[#2059: 'Dynamic Changes' by SomeRandomOwl at commit 5bbe752b87](https://github.com/NovaSector/NovaSector/pull/2059)
[#2079: 'Tweaks to the Interlink disposal access/room' by iliyaxox at commit 515c3775f5](https://github.com/NovaSector/NovaSector/pull/2079)
[#2101: 'trims down akula language description' by tf-4 at commit 896a365a6a](https://github.com/NovaSector/NovaSector/pull/2101)
[#2127: '[MIRROR] [READY] the unfuckening of clothing rendering' by NovaBot13 at commit cd96884276](https://github.com/NovaSector/NovaSector/pull/2127)

**Comment by FlufflesTheDog** [comment]
Fixed by #3096
