### ISSUE TITLE
welding mask removes snouts and masks/eyewear (until put back on) and welding goggles do not have other worn or inhand sprites anymore

### ISSUE THREAD

**Issue by ghost** [NovaSector/NovaSector#2146]
## Issue Summary
as title, the welding mask will remove your snout and anything below it after being lifted/taken off until you re-equip a mask and eyewear, and welding goggles only have the inhand and worn sprite for being down now, they do not change regardless of flipped or not

## Reproduction:
as summary i dont want to retype everything

**Comment by Sadboysuss** [comment]
Doesn't seem to be an issue anymore, comment here if you still see it happening.
This is marked for cleanup and will be auto-closed in 7 days
