### ISSUE TITLE
Welding Goggles Adjustment Problem

### ISSUE THREAD

**Issue by Sk0rpios** [NovaSector/NovaSector#2155]
Reporting client version: 514.1589

## Issue Summary
Welding goggles do not change sprite when adjusted up, though the darkening effect still changes. The welding gas mask cannot be adjusted at all.

## Round ID:
[10665](https://scrubby.melonmesa.com/round/10665)

## Testmerges:
- [[MODULAR] Adds a dice roll emote](https://github.com/NovaSector/NovaSector/pull/1556)
- [[PORT] [SEMI-MODULAR] [JANK] Ports the lovely Character Directory which was ported from Coyote Bayou](https://github.com/NovaSector/NovaSector/pull/183)
- [Ooey Gooey Slimegirl Buffs Vol. 1](https://github.com/NovaSector/NovaSector/pull/1661)
- [[SEMI-MODULAR] Allows users to customize fragile's brute/burn mods, adds physiology damage mult to health analyzers](https://github.com/NovaSector/NovaSector/pull/1800)
- [Adds the Deep Space deathmatch map](https://github.com/NovaSector/NovaSector/pull/1999)
- [Dynamic Changes](https://github.com/NovaSector/NovaSector/pull/2059)

## Reproduction:
Put on welding goggles.
Try to adjust them up.
See the sprite not change in hand or on the character sprite.
Do the same for welding gas mask.
See nothing change at all.

**Comment by Sadboysuss** [comment]
Doesn't seem to be an issue anymore, comment here if you still see it happening.
This is marked for cleanup and will be auto-closed in 7 days
