### ISSUE TITLE
Implanted items will drop to the floor or delete if attempting to put in backpack.

### ISSUE THREAD

**Issue by brokenOculus** [NovaSector/NovaSector#2161]
Reporting client version: 514.1589

## Issue Summary

Nodrop items will still drop if attempting to put them in bag, such as implanted tools, or even the genetics-infused goliath arm.

## Round ID:
[10667](https://scrubby.melonmesa.com/round/10667)

## Testmerges:
- [[MODULAR] Adds a dice roll emote](https://github.com/NovaSector/NovaSector/pull/1556)
- [[PORT] [SEMI-MODULAR] [JANK] Ports the lovely Character Directory which was ported from Coyote Bayou](https://github.com/NovaSector/NovaSector/pull/183)
- [Ooey Gooey Slimegirl Buffs Vol. 1](https://github.com/NovaSector/NovaSector/pull/1661)
- [[SEMI-MODULAR] Allows users to customize fragile's brute/burn mods, adds physiology damage mult to health analyzers](https://github.com/NovaSector/NovaSector/pull/1800)
- [Adds the Deep Space deathmatch map](https://github.com/NovaSector/NovaSector/pull/1999)
- [Dynamic Changes](https://github.com/NovaSector/NovaSector/pull/2059)

## Reproduction:

Simply start off with one of the numerous tool-arm implants, attempt to put it in your bag with "E" key, it will drop to the ground. Genetics-infused Goliath arm will simply delete if 'dropped'.

**Comment by Sadboysuss** [comment]
No drop items are no drop because they're not supposed to be carried normally or even appear by normal means, if Nova has these items then they should edit them to no longer be no drop or remove them from being accessible by players.

**Comment by FlufflesTheDog** [comment]
It is normal for some things, like retractable (eg implant) tools to be tagged nodrop, it's like that on tg too
Fixed by #2170
