### ISSUE TITLE
Rack Unwrenchable

### ISSUE THREAD

**Issue by Sk0rpios** [NovaSector/NovaSector#2171]
Reporting client version: 514.1589

## Issue Summary
When attempting to deconstruct a rack with a wrench or wrench variant, the wrench will just be put onto the rack instead of deconstructing it.

## Round ID:
[10673](https://scrubby.melonmesa.com/round/10673)

## Testmerges:
- [[MODULAR] Adds a dice roll emote](https://github.com/NovaSector/NovaSector/pull/1556)
- [[PORT] [SEMI-MODULAR] [JANK] Ports the lovely Character Directory which was ported from Coyote Bayou](https://github.com/NovaSector/NovaSector/pull/183)
- [Ooey Gooey Slimegirl Buffs Vol. 1](https://github.com/NovaSector/NovaSector/pull/1661)
- [[SEMI-MODULAR] Allows users to customize fragile's brute/burn mods, adds physiology damage mult to health analyzers](https://github.com/NovaSector/NovaSector/pull/1800)
- [Adds the Deep Space deathmatch map](https://github.com/NovaSector/NovaSector/pull/1999)
- [Dynamic Changes](https://github.com/NovaSector/NovaSector/pull/2059)

## Reproduction:
Build or find a rack.
Attempt to deconstruct the rack with a wrench using right click.
Watch the wrench be placed onto the rack instead.

**Comment by Raldin** [comment]
I'm experiencing the same issue with railings. Wirecutters hit them instead of snipping them into rods.

**Comment by FlufflesTheDog** [comment]
Fixed by #3096 (and the upstream attack chain stuff)
