### ISSUE TITLE
Smoker quirk is nonfunctional

### ISSUE THREAD

**Issue by Quink-Fix** [NovaSector/NovaSector#2206]
## Round ID:
N/A - reproduce-able 

## Testmerges:
[#1556: '[MODULAR] Adds a dice roll emote' by nikothedude at commit d7010f36b4](https://github.com/NovaSector/NovaSector/pull/1556)
[#183: '[PORT] [SEMI-MODULAR] [JANK] Ports the lovely Character Directory which was ported from Coyote Bayou' by W4rd3nn at commit e1672d35dd](https://github.com/NovaSector/NovaSector/pull/183)
[#1661: 'Ooey Gooey Slimegirl Buffs Vol. 1' by Nerev4r at commit d2b9e5df9f](https://github.com/NovaSector/NovaSector/pull/1661)
[#1999: 'Adds the Deep Space deathmatch map' by honkpocket at commit ab821ba91a](https://github.com/NovaSector/NovaSector/pull/1999)
[#2059: 'Dynamic Changes' by SomeRandomOwl at commit 5bbe752b87](https://github.com/NovaSector/NovaSector/pull/2059)
[#2134: 'Adds more spawn location to moldies' by honkpocket at commit 6baeef8337](https://github.com/NovaSector/NovaSector/pull/2134)
[#2088: 'Ouroboros rejigging' by Ketrai at commit bb9f5ef514](https://github.com/NovaSector/NovaSector/pull/2088)
[#2141: '[MIRROR] Higher capacity SMES variant for low maintenance areas; miners can access their maintenance area on mining base, gulag no longer saps all power from the main base' by NovaBot13 at commit 7e601feb05](https://github.com/NovaSector/NovaSector/pull/2141)

## Reproduction:
1. Take the smoker quirk.
2. Wait for your cravings to kick in.
3. Smoke the quirk's chosen brand of cigs.
4. Note that no matter how much you smoke, your cravings will not go away.

**Comment by Quink-Fix** [comment]
![image](https://github.com/NovaSector/NovaSector/assets/88389357/09f73d4d-a512-4dd4-a853-22c0369bb611)
![image1](https://github.com/NovaSector/NovaSector/assets/88389357/41e2bca6-271e-4f20-b7e8-a4822f243af6)

**Comment by Sadboysuss** [comment]
Doesn't seem to be an issue anymore, comment here if you still see it happening.
This is marked for cleanup and will be auto-closed in 7 days
