### ISSUE TITLE
Geared Assistants trait resetting custom loadouts

### ISSUE THREAD

**Issue by wivernshy** [NovaSector/NovaSector#2328]
Reporting client version: 515.1633

## Issue Summary
The 'geared assistants' station trait with replace every customized item in a character loadout with default versions.
Example image: The croptop should be pink, plushie should be named 'Mini Granite', etc.
![image](https://github.com/NovaSector/NovaSector/assets/46330016/04e37608-b85f-4ae1-9015-c1e7d27c94a8)

## Round ID:
[10763](https://scrubby.melonmesa.com/round/10763)

## Testmerges:
- [[MODULAR] Adds a dice roll emote](https://github.com/NovaSector/NovaSector/pull/1556)
- [[PORT] [SEMI-MODULAR] [JANK] Ports the lovely Character Directory which was ported from Coyote Bayou](https://github.com/NovaSector/NovaSector/pull/183)
- [Ooey Gooey Slimegirl Buffs Vol. 1](https://github.com/NovaSector/NovaSector/pull/1661)
- [Adds more spawn location to moldies](https://github.com/NovaSector/NovaSector/pull/2134)
- [Ouroboros rejigging](https://github.com/NovaSector/NovaSector/pull/2088)
- [[Semi-Modular] Ports over additional Crusher varients from monkestation](https://github.com/NovaSector/NovaSector/pull/2238)
- [Neuters synthetic electrical damage ](https://github.com/NovaSector/NovaSector/pull/2300)
- [Ports effigy-se #814 (Leashes)](https://github.com/NovaSector/NovaSector/pull/2306)

## Reproduction:
Join as an assistant during a round with the GA trait, have a named/recolored/etc item in your loadout
Weep as all your beautifully customized stuff has been stolen and replaced by the bug goblins

**Comment by FlufflesTheDog** [comment]
Should be fixed as of #3988
