### ISSUE TITLE
Slime revival instantly round-removing the person being revived.

### ISSUE THREAD

**Issue by OzzyMcPseudonym** [NovaSector/NovaSector#2536]
## Issue Summary
Upon being revived as a a slimeperson with plasma, I instantly died and didn't leave a core. I don't have any reason to suspect I was DNR for any reason. I got a bunch of chat messages about "[body part] splatters with an unnerving squelch." for each limb and head, and a message about "Your body completely dissolves, collapsing outwards!" and unapplying all of my quirks.

## Round ID:

10844

## Testmerges:

 This was on master commit
[5c8e789cdd04edc615c5a5ad1cdc1fde89402a34](https://github.com/NovaSector/NovaSector/commit/5c8e789cdd04edc615c5a5ad1cdc1fde89402a34) which has the slimepeople rework test merged.
## Reproduction:

Die as a slime
Have someone pour plasma on your core to heal you
Die instantaneously the microsecond you arrive in crit. Don't leave behind a core, thus round-removing you.

**Comment by OzzyMcPseudonym** [comment]
I should specify now that the round in question is over, my character who went through this bug was named Goobo Caeruleus.

**Comment by Sadboysuss** [comment]
Still an issue?

**Comment by Nerev4r** [comment]
shrug??????
