### ISSUE TITLE
Changing professions taxes you on your new department 

### ISSUE THREAD

**Issue by annikaRU** [NovaSector/NovaSector#257]
## Issue Summary

When the HoP changes your job to a new department the techfab will charge your account for stuff you make

## Testmerges:

- [[NON-MODULAR] image qdels, hard deletes, oh my! searching for solutions to the crashing.](https://github.com/NovaSector/NovaSector/pull/250)
- [[TM ONLY] [EARLY MIRROR] Revert "Makes immerse use weakrefs", prioritizing some ref removal lines instead](https://github.com/NovaSector/NovaSector/pull/238)
- [Period Era Re-Enactment: Basic autopunctuation](https://github.com/NovaSector/NovaSector/pull/84)
- [[Semi-modular] Gives Xeno-hybrids some xeno-organs in trade for high temperature weakness](https://github.com/NovaSector/NovaSector/pull/91)
- [Kahraman, after collecting dust for 100 years, finally has its own content, hear ye guncargo naysayers and weep](https://github.com/NovaSector/NovaSector/pull/98)
- [Antag optin ](https://github.com/NovaSector/NovaSector/pull/121)
- [Expands the rapid construction fabricator's appliances to be more than four (4) things!](https://github.com/NovaSector/NovaSector/pull/130)
- [[PORT] [SEMI-MODULAR] [100% FREE LAG] Chat Colors](https://github.com/NovaSector/NovaSector/pull/157)
- [Masquerade masks can now be toggled to hide your identity](https://github.com/NovaSector/NovaSector/pull/218)

## Reproduction:

Have the HOP change your profession E.G: Assistant to Geneticist, print something from a techfab and it'll charge you

there was a PR that was never merged that was supposed to resolve this and never got merged

**Comment by Sadboysuss** [comment]
Lathe tax is no longer a thing
