### ISSUE TITLE
lighting a smoke pipe with anything inside it will cause the texture to error

### ISSUE THREAD

**Issue by PowerfulAtom111** [NovaSector/NovaSector#2671]
Reporting client version: 515.1639

## Issue Summary
when i pack anything into the smoking pipe (meerschaum, you know the one) and smoke it, the texture ERRORs and you have a big ole pink-and-black checkerboard on your character's face

## Round ID:
[10905](https://scrubby.melonmesa.com/round/10905)

## Testmerges:
- [[PORT] [SEMI-MODULAR] [JANK] Ports the lovely Character Directory which was ported from Coyote Bayou](https://github.com/NovaSector/NovaSector/pull/183)
- [Ooey Gooey Slimegirl Buffs Vol. 1](https://github.com/NovaSector/NovaSector/pull/1661)
- [Ouroboros rejigging](https://github.com/NovaSector/NovaSector/pull/2088)
- [Freerunning is no longer needed to flip](https://github.com/NovaSector/NovaSector/pull/2525)
- [[SEMI-MODULAR] A few taur fixes + constrict legs fix](https://github.com/NovaSector/NovaSector/pull/2651)
- [[SEMI-MODULAR] Taur rework Pt. 2: Quadruped taurs (Part one)](https://github.com/NovaSector/NovaSector/pull/1976)

## Reproduction:
1. dry something
2. put it in your pipe
3. smoke it

**Comment by PowerfulAtom111** [comment]
this happens on the latest version of BYOND and the recommended version for Nova Sector

**Comment by FlufflesTheDog** [comment]
Fixed by https://github.com/NovaSector/NovaSector/pull/2892
