### ISSUE TITLE
Welding will still flash a moth character even with proper eye protection.

### ISSUE THREAD

**Issue by Ford-Defect** [NovaSector/NovaSector#2972]
Reporting client version: 514.1589

## Issue Summary

When welding things (broken tiles, damaged glass) as a moth character, I'm still getting the screen flash effect along with the "your eyes sting a little" message, even while wearing welding goggles or a welding mask.

## Round ID:
[11013](https://scrubby.melonmesa.com/round/11013)

## Testmerges:
- [[PORT] [SEMI-MODULAR] [JANK] Ports the lovely Character Directory which was ported from Coyote Bayou](https://github.com/NovaSector/NovaSector/pull/183)
- [Ooey Gooey Slimegirl Buffs Vol. 1](https://github.com/NovaSector/NovaSector/pull/1661)
- [[SEMI-MODULAR] Taur rework Pt. 2: Quadruped taurs (Part one)](https://github.com/NovaSector/NovaSector/pull/1976)
- [Flashbangs now inform user if the security level is green, and during green alerts they must be ctrl+clicked to arm](https://github.com/NovaSector/NovaSector/pull/2553)
- [[TESTING ONLY] Debugging overlay cap being reached with taur parts](https://github.com/NovaSector/NovaSector/pull/2754)
- [Blueshield QOL with other code cleanup](https://github.com/NovaSector/NovaSector/pull/2816)
- [[SEMI-MODULAR] Telecomms Specialist](https://github.com/NovaSector/NovaSector/pull/2757)
- [[MODULAR] Add mggaow, prbt and mrrp emotes](https://github.com/NovaSector/NovaSector/pull/2886)
- [Pipe Dreams: Disposals is actually usable as an escape again](https://github.com/NovaSector/NovaSector/pull/2852)

## Reproduction:

Play as a moth character, wear proper welding protection, attempt to do a task that requires welding, get flashed.

**Comment by Ford-Defect** [comment]
Before the "fix" on welding brightness you could get by as a moth with standard welding protection. If this is the way it's supposed to be that's pretty stupid tbh.

**Comment by Sadboysuss** [comment]
this isn't a bug as per upstream's intention, you can make a feature request to change this on Nova though

**Comment by Sadboysuss** [comment]
Since this isn't a bug - closing this, you can make a feature request for changing it on Nova though
