### ISSUE TITLE
Mining MODsuit Suit Storage Error

### ISSUE THREAD

**Issue by TripleShades** [NovaSector/NovaSector#3053]
Reporting client version: 515.1640

## Issue Summary
Mining MODsuit suit storage refuses to hold items that pertain to mining (crushers + variants, resonators, mining scanner, etc)

## Round ID:
[11039](https://scrubby.melonmesa.com/round/11039)

## Testmerges:
- [[PORT] [SEMI-MODULAR] [JANK] Ports the lovely Character Directory which was ported from Coyote Bayou](https://github.com/NovaSector/NovaSector/pull/183)
- [Ooey Gooey Slimegirl Buffs Vol. 1](https://github.com/NovaSector/NovaSector/pull/1661)
- [[SEMI-MODULAR] Taur rework Pt. 2: Quadruped taurs (Part one)](https://github.com/NovaSector/NovaSector/pull/1976)
- [Flashbangs now inform user if the security level is green, and during green alerts they must be ctrl+clicked to arm](https://github.com/NovaSector/NovaSector/pull/2553)
- [[TESTING ONLY] Debugging overlay cap being reached with taur parts](https://github.com/NovaSector/NovaSector/pull/2754)
- [[SEMI-MODULAR] Telecomms Specialist](https://github.com/NovaSector/NovaSector/pull/2757)
- [Pipe Dreams: Disposals is actually usable as an escape again](https://github.com/NovaSector/NovaSector/pull/2852)
- [The End of the Galactic Materials Market: Economy shakeup](https://github.com/NovaSector/NovaSector/pull/2498)
- [Doubles SMES output and input ability per tier, QOL Buff to Solar power generation](https://github.com/NovaSector/NovaSector/pull/3005)
- [Wawastation automapper fixes/updates](https://github.com/NovaSector/NovaSector/pull/3029)

## Reproduction:
Wear and deploy a mining MODsuit
Try and store mining-related tools into the suit storage
It doesn't let you
Become upset because now you have to lug your tool around in your hand

**Comment by Sadboysuss** [comment]
explorer suit works like this but mining modsuit doesn't, seems like a consistency issue on /tg/'s side

**Comment by TripleShades** [comment]
This only happened after a modsuit/storage pr on Nova, which I cannot find currently. It was testmerged for a while, as well.

**Comment by Sadboysuss** [comment]
it's also not working on /tg/ master, tested it

**Comment by Sadboysuss** [comment]
https://github.com/tgstation/tgstation/issues/85332
