### ISSUE TITLE
Using the interface to place objects on tables is fucked up

### ISSUE THREAD

**Issue by Krypandenej** [NovaSector/NovaSector#3321]
Reporting client version: 515.1637

## Issue Summary

Attempting to place an object on any table, rack, or otherwise by using the alt-click interface will place it in the southwestern corner of it, usually completely off the table.

## Round ID:
[11121](https://scrubby.melonmesa.com/round/11121)

## Testmerges:
- [Flashbangs now inform user if the security level is green, and during green alerts they must be ctrl+clicked to arm (only affects security)](https://github.com/NovaSector/NovaSector/pull/2553)
- [[TESTING ONLY] Debugging overlay cap being reached with taur parts](https://github.com/NovaSector/NovaSector/pull/2754)
- [Pipe Dreams: Disposals is actually usable as an escape again](https://github.com/NovaSector/NovaSector/pull/2852)
- [The End of the Galactic Materials Market: Economy shakeup](https://github.com/NovaSector/NovaSector/pull/2498)
- [Remove stamcrit from death degradation, removing endless stamcrit loop](https://github.com/NovaSector/NovaSector/pull/3200)
- [[MIRROR] Adds Character Loadout Tab to preferences (with just a small handful of items to start) [MDB IGNORE]](https://github.com/NovaSector/NovaSector/pull/2984)

## Reproduction:
Get object, like drinking glass
Alt click structure like table
Click table on alt-interface with said object in-hand

**Comment by Sadboysuss** [comment]
pr already opened and linked
