### ISSUE TITLE
Incorrect ammo capacity listing

### ISSUE THREAD

**Issue by Zorazi-Teo-Daedalus** [NovaSector/NovaSector#3470]
Reporting client version: 515.1637

## Issue Summary
Both the Miecz magazine and the .27-54 Cesarzowa piercing ammunition box state in their description text on the Cargo console and their examine text that they hold eighteen rounds, rather than the updated twenty eight. I would imagine this is the case for the .27-54 rubber ammunition box as well.

## Round ID:
[11160](https://scrubby.melonmesa.com/round/11160)

## Testmerges:
- [Flashbangs now inform user if the security level is green, and during green alerts they must be ctrl+clicked to arm (only affects security)](https://github.com/NovaSector/NovaSector/pull/2553)
- [[TESTING ONLY] Debugging overlay cap being reached with taur parts](https://github.com/NovaSector/NovaSector/pull/2754)
- [The End of the Galactic Materials Market: Economy shakeup](https://github.com/NovaSector/NovaSector/pull/2498)
- [[MIRROR] Adds Character Loadout Tab to preferences (with just a small handful of items to start) [MDB IGNORE]](https://github.com/NovaSector/NovaSector/pull/2984)
- [Adds the System Shock quirk.](https://github.com/NovaSector/NovaSector/pull/3335)
- [Unsteady Quirk: Customizable chance to fall down upon taking blunt damage](https://github.com/NovaSector/NovaSector/pull/3297)
- [You can choose the type of footstep sound you make while barefoot](https://github.com/NovaSector/NovaSector/pull/3404)
- [Colony wall heater qol & fixes](https://github.com/NovaSector/NovaSector/pull/3428)
- [Ashwalker QOL, New Ritual and Aging Ritual changes](https://github.com/NovaSector/NovaSector/pull/3447)

## Reproduction:
Read console. Read magazine description. Read ammo box description. Count the rounds. Find overlooked mistake.

**Comment by Sadboysuss** [comment]
easy to fix by updating the description to the updated feature

**Comment by FlufflesTheDog** [comment]
Fixed by #4228
