### ISSUE TITLE
Suffocation Damage Does not Apply and Cannot be Healed to a Gamebreaking Extent

### ISSUE THREAD

**Issue by Knightscholar** [NovaSector/NovaSector#3573]
Reporting client version: 515.1636

## Issue Summary

Internals are not needed, Strangling does not work. Suffocation damage does not apply at all when it should, cannot be healed naturally once it's applied.

## Round ID:
[11187](https://scrubby.melonmesa.com/round/11187)

## Testmerges:
- [Flashbangs now inform user if the security level is green, and during green alerts they must be ctrl+clicked to arm (only affects security)](https://github.com/NovaSector/NovaSector/pull/2553)
- [[TESTING ONLY] Debugging overlay cap being reached with taur parts](https://github.com/NovaSector/NovaSector/pull/2754)
- [The End of the Galactic Materials Market: Economy shakeup](https://github.com/NovaSector/NovaSector/pull/2498)
- [[MIRROR] Adds Character Loadout Tab to preferences (with just a small handful of items to start) [MDB IGNORE]](https://github.com/NovaSector/NovaSector/pull/2984)
- [You can choose the type of footstep sound you make while barefoot](https://github.com/NovaSector/NovaSector/pull/3404)
- [SerenityStation - New Planetary Station Map](https://github.com/NovaSector/NovaSector/pull/3040)
- [Improves the Gear Harness slots](https://github.com/NovaSector/NovaSector/pull/3449)
- [(BOUNTY) Lithovore Stomach Option](https://github.com/NovaSector/NovaSector/pull/3439)

## Reproduction:

Humans, Anthropomorphs, Slimes and potentially others (not tested by me yet) do not require internals to not suffocate in space, and do not sustain Suffocation damage when strangled as part of a grab. Additionally Suffocation damage does not naturally decay to 0, and requires either manual healing (tested with Oxyloss Medigun), or the use of internals with O2 (potentially N2 for N2 breathers).

Not Needing Internals in Space
1) Enter Space
2) Do not put on internals
3) Wait until suffocation ordinarily would begin
4) Do not suffocate

Not Taking Damage from Strangling
1) Become grabbed by the neck
2) Become strangled
3) Do not begin suffocating

Suffocation Damage not Healing
1) Inflict Suffocation damage on yourself. Methods used in testing were CO2 inhalation from a CO2 jetpack, and a tank with a release pressure of 0 used as internals
2) Wait for when it would ordinarily tick down.
3) Experience it not ticking down. Additionally, the large O2 icon in the top right of the screen that is ordinarily used to to denote suffocation will not disappear

NOTABLE DETAIL: The large O2 icon in the corner of the screen is a real suffocation icon, given that it gives the "CAN'T... BREATHE..." negative moodlet.

Healing Suffocation Damage
Either
a) Use a tank with O2 set to a reasonable release value. This should cause Suffocation to tick down as it ordinarily should. This will also instantly remove the large O2 icon used to denote suffocating, as well as the moodlet associated with it.

or

b) Use an Oxyloss Medigun shot. This should heal as it should

or

c) Use Convermol. This should heal as it should. Theoretically, other chems that heal it should work fine also.

Small Detail: If using (b) or (c) for Healing Suffocation Damage, the large O2 icon in the top right of the screen will not disappear even if Suffocation damage hits 0.

**Comment by FlufflesTheDog** [comment]
Everything but the moodlets should be fixed by #3588. Unsure if it'll do anything with the moodlets
