### ISSUE TITLE
The portable chem mixer doesn't accept beakers

### ISSUE THREAD

**Issue by Krypandenej** [NovaSector/NovaSector#3576]
Reporting client version: 515.1640

## Issue Summary
This is exactly what it says on the tin. Likely broken dues to some duffel bag related update.

## Round ID:
[11188](https://scrubby.melonmesa.com/round/11188)

## Testmerges:
- [Flashbangs now inform user if the security level is green, and during green alerts they must be ctrl+clicked to arm (only affects security)](https://github.com/NovaSector/NovaSector/pull/2553)
- [[TESTING ONLY] Debugging overlay cap being reached with taur parts](https://github.com/NovaSector/NovaSector/pull/2754)
- [The End of the Galactic Materials Market: Economy shakeup](https://github.com/NovaSector/NovaSector/pull/2498)
- [[MIRROR] Adds Character Loadout Tab to preferences (with just a small handful of items to start) [MDB IGNORE]](https://github.com/NovaSector/NovaSector/pull/2984)
- [You can choose the type of footstep sound you make while barefoot](https://github.com/NovaSector/NovaSector/pull/3404)
- [SerenityStation - New Planetary Station Map](https://github.com/NovaSector/NovaSector/pull/3040)
- [Improves the Gear Harness slots](https://github.com/NovaSector/NovaSector/pull/3449)
- [(BOUNTY) Lithovore Stomach Option](https://github.com/NovaSector/NovaSector/pull/3439)

## Reproduction:
1. Close portable chem mixer
2. Attempt to insert beaker into faucet

**Comment by OrionTheFox** [comment]
Sounds like another upstream attack-chain bug

**Comment by FlufflesTheDog** [comment]
Fixed by https://github.com/NovaSector/NovaSector/pull/3836
