### ISSUE TITLE
Tram Tramming

### ISSUE THREAD

**Issue by TripleShades** [NovaSector/NovaSector#3673]
Reporting client version: 515.1640

## Issue Summary
![image](https://github.com/NovaSector/NovaSector/assets/6299921/6311481d-0795-4d78-8b3a-08f86073b3ec)
Yeah I dont think it's supposed to do this.

## Round ID:
[11210](https://scrubby.melonmesa.com/round/11210)

## Testmerges:
- [[TESTING ONLY] Debugging overlay cap being reached with taur parts](https://github.com/NovaSector/NovaSector/pull/2754)
- [[MIRROR] Adds Character Loadout Tab to preferences (with just a small handful of items to start) [MDB IGNORE]](https://github.com/NovaSector/NovaSector/pull/2984)
- [(BOUNTY) Lithovore Stomach Option](https://github.com/NovaSector/NovaSector/pull/3439)
- [[MODULAR] More Deployable Turret Work + Ruins for them](https://github.com/NovaSector/NovaSector/pull/3464)
- [Serenity Ambience DLC - Mushroom theme, several more ambience tracks for the mushroom caves and even some for the forest!](https://github.com/NovaSector/NovaSector/pull/3668)

## Reproduction:
Load up Tramstation
Observe, do not move
Wait for the round to start
Call the tram to another area from the center (You can likely follow the tram for this part)
Watch it do an Uh Oh

**Comment by SomeRandomOwl** [comment]
Very likely a upstream issue

**Comment by Sadboysuss** [comment]
upstream issue https://github.com/tgstation/tgstation/issues/85171
