### ISSUE TITLE
[SerenityStation] Compilation of assorted map bugs

### ISSUE THREAD

**Issue by OrionTheFox** [NovaSector/NovaSector#3675]
## Issue Summary

<details>
<summary> Kitchen has no fire alarm </summary>

![image](https://github.com/NovaSector/NovaSector/assets/76465278/ddc0f9b8-3886-4b9d-9acd-b23367d94752)

</details>

<details>
<summary> Kitchen is missing 3 firelocks </summary>

![image](https://github.com/NovaSector/NovaSector/assets/76465278/2a74176d-387a-4b9c-8c6e-a93f66f97e11)

</details>
<details>
<summary> Stray decals on Robotics walls </summary>

![image](https://github.com/NovaSector/NovaSector/assets/76465278/962ae02d-41f0-40ec-94ca-15df3f16682b)
</details>

<details>
<summary> Arrivals Transport Airlocks have incorrect dir-access directions (also have a name mismatch: the dir-access 2 are named "Arrivals Airlocks" and the external 2 "Transport Airlocks")</summary>

![image](https://github.com/NovaSector/NovaSector/assets/76465278/2c8149c1-5183-4772-87f7-9af06d13fc67)
</details>

<details>
<summary> Odd cut-off cable behind the bridge </summary>

![image](https://github.com/NovaSector/NovaSector/assets/76465278/b625843e-0f86-47a3-9c4a-437616e42014)
</details>

<details>
<summary> Lavaland Raptors use icebox variants (which are visibly fluffier and insulated, appearing jarring on lavaland)</summary>

![347861654-c8ae96f4-794e-4c99-9938-bbfad0f438b8](https://github.com/user-attachments/assets/efffed40-2377-4fb2-8dfa-ce279f3d71a7)
</details>

<details>
<summary> Extra light bulb in a rec room bathroom stall</summary>

![image](https://github.com/user-attachments/assets/90cb41f1-72e1-48a8-950a-e85c52270e7e)
</details>

## Round ID:
N/A (Several rounds, round-start)

## Testmerges:
- [[TESTING ONLY] Debugging overlay cap being reached with taur parts](https://github.com/NovaSector/NovaSector/pull/2754)
- [[MIRROR] Adds Character Loadout Tab to preferences (with just a small handful of items to start) [MDB IGNORE]](https://github.com/NovaSector/NovaSector/pull/2984)
- [(BOUNTY) Lithovore Stomach Option](https://github.com/NovaSector/NovaSector/pull/3439)
- [[MODULAR] More Deployable Turret Work + Ruins for them](https://github.com/NovaSector/NovaSector/pull/3464)
- [Serenity Ambience DLC - Mushroom theme, several more ambience tracks for the mushroom caves and even some for the forest!](https://github.com/NovaSector/NovaSector/pull/3668)

**Comment by Zergspower** [comment]
Add in: Lavaland raptors are flagged to use icebox variants which are far far poofier and oddly jarring to see in lavaland.
![image](https://github.com/NovaSector/NovaSector/assets/22140677/c8ae96f4-794e-4c99-9938-bbfad0f438b8)

**Comment by Sadboysuss** [comment]
this map has a mining area like icebox but also lavaland? This slightly confuses me
