### ISSUE TITLE
NTOS Error with Recolorables

### ISSUE THREAD

**Issue by TetrakoHateThis** [NovaSector/NovaSector#3676]
## Issue Summary
While digging through clothing items for a future suggestion, I found a few recolorable items that trigger an NTOS error.
The ones I noticed that caused the issue were:
Red Suit and Skirt
Red Suit and Striped Skirt
Black Bra and Skirt
Swept Skirt

Image included of the NTOS error popping up.

![skirtNTOS](https://github.com/NovaSector/NovaSector/assets/81869793/2c6856bb-3ee6-46fc-b03d-d5936373e0f8)

## Round ID:
[11211](https://scrubby.melonmesa.com/round/11211)

## Testmerges:
[#2754: '[TESTING ONLY] Debugging overlay cap being reached with taur parts' by vinylspiders at commit c6104e5204](https://github.com/NovaSector/NovaSector/pull/2754)
[#2984: '[MIRROR] Adds Character Loadout Tab to preferences (with just a small handful of items to start) [MDB IGNORE]' by NovaBot13 at commit 69994db90f](https://github.com/NovaSector/NovaSector/pull/2984)
[#3439: '(BOUNTY) Lithovore Stomach Option' by CandleJaxx at commit 7222cfbdae](https://github.com/NovaSector/NovaSector/pull/3439)
[#3464: '[MODULAR] More Deployable Turret Work + Ruins for them' by Zenitheevee at commit 96dff24cbf](https://github.com/NovaSector/NovaSector/pull/3464)
[#3668: 'Serenity Ambience DLC - Mushroom theme, several more ambience tracks for the mushroom caves and even some for the forest!' by GoldenAlpharex at commit 1535c14467](https://github.com/NovaSector/NovaSector/pull/3668)

## Reproduction:
Go to Loadout
Equip any of the aforementioned items above.
Press 'Recolor'

**Comment by FlufflesTheDog** [comment]
Should be fixed!
