### ISSUE TITLE
Echolocation bug

### ISSUE THREAD

**Issue by CrafticalDecoy** [NovaSector/NovaSector#3702]
Reporting client version: 515.1639

## Issue Summary
When an AI uses a holopad or changes their hologram form, the new form is plastered on everyone using the echolocation. 

## Round ID:
[11218](https://scrubby.melonmesa.com/round/11218)

## Testmerges:
- [[TESTING ONLY] Debugging overlay cap being reached with taur parts](https://github.com/NovaSector/NovaSector/pull/2754)
- [[MIRROR] Adds Character Loadout Tab to preferences (with just a small handful of items to start) [MDB IGNORE]](https://github.com/NovaSector/NovaSector/pull/2984)
- [(BOUNTY) Lithovore Stomach Option](https://github.com/NovaSector/NovaSector/pull/3439)
- [[MODULAR] More Deployable Turret Work + Ruins for them](https://github.com/NovaSector/NovaSector/pull/3464)
- [Serenity Ambience DLC - Mushroom theme, several more ambience tracks for the mushroom caves and even some for the forest!](https://github.com/NovaSector/NovaSector/pull/3668)
- [Uh oh! The NT board of workplace safety is trying to blacklist the Akhter Co. Prybar!](https://github.com/NovaSector/NovaSector/pull/3635)
- [[PORT] Assorted Liquids Patches](https://github.com/NovaSector/NovaSector/pull/3663)

## Reproduction:

Have an AI change their form while using a holopad (maybe without even using the holopad) and it bugs out the echolocation forever. Ahealing doesn't work, neither does removing and putting the trait once more, and the last tried one that also didn't work is reloading character preferences.

Shown echolocation.
![image](https://github.com/NovaSector/NovaSector/assets/33381354/c627e519-7000-4c87-8480-fcfe4b52f21f)

Actual form.
![image](https://github.com/NovaSector/NovaSector/assets/33381354/7b77d344-3df0-4fa8-b26b-546d523a138d)

**Comment by PuppyVenom** [comment]
I noticed this too, I couldn't figure out the cause, but did realize it only impacts organics. If you look at my screenshot it doesn't change the echo of the synth on screen, but every organic is impacted.
![weirdecho2](https://github.com/user-attachments/assets/9a26db9c-4f95-49b6-8d52-00c891ee36c5)

**Comment by Sadboysuss** [comment]
https://github.com/tgstation/tgstation/pull/86604
