### ISSUE TITLE
Viruses Curing Themselves

### ISSUE THREAD

**Issue by sqnztb** [NovaSector/NovaSector#384]
Reporting client version: 515.1623

## Issue Summary
Beneficial viruses are sometimes being cured off on their own. Made a standard SR/NR in this round with a synaptizine cure. Never took synap and yet:

![image](https://github.com/NovaSector/NovaSector/assets/28007787/e86921b3-d35a-4da6-bdfc-24314e6406b1)

This has happened on a few different rounds. 

## Round ID:
[10506](https://scrubby.melonmesa.com/round/10506)

## Testmerges:
- [Antag optin ](https://github.com/NovaSector/NovaSector/pull/121)
- [[TM ONLY] [EARLY MIRROR] Revert "Makes immerse use weakrefs", prioritizing some ref removal lines instead](https://github.com/NovaSector/NovaSector/pull/238)
- [[MODULAR] Removes Arbitrary Loadout Restrictions](https://github.com/NovaSector/NovaSector/pull/58)
- [[MODULAR] Chat color tweaks!](https://github.com/NovaSector/NovaSector/pull/323)
- [Kahraman, after collecting dust for 100 years, finally has its own content, hear ye guncargo naysayers and weep](https://github.com/NovaSector/NovaSector/pull/98)
- [[TM-ONLY] Testing chatmessage debug](https://github.com/NovaSector/NovaSector/pull/275)
- [[Testing] Fixing a potential issue with liquid turfs](https://github.com/NovaSector/NovaSector/pull/356)

## Reproduction:
Infect self with virus. Wait? RNG? Hope and pray?

**Comment by nikothedude** [comment]
https://github.com/tgstation/tgstation/pull/79854 

Not a bug

**Comment by sqnztb** [comment]
I swear I searched for PR's and issue reports on tg before I submitted this. Good to know.
