### ISSUE TITLE
Character Loadout - Causing action spam?

### ISSUE THREAD

**Issue by CreampuffSugar** [NovaSector/NovaSector#3892]
Reporting client version: 515.1637

## Issue Summary

Whenever I go to the loadout menu I get an issue where the chat is spammed with messages saying I'm doing too many things in a minute or second. I'm worried I'm gonna get banned for being mistaken for a lag bot or something.

## Round ID:
[11278](https://scrubby.melonmesa.com/round/11278)

## Testmerges:
- [[TESTING ONLY] Debugging overlay cap being reached with taur parts](https://github.com/NovaSector/NovaSector/pull/2754)
- [Serenity Ambience DLC - Mushroom theme, several more ambience tracks for the mushroom caves and even some for the forest!](https://github.com/NovaSector/NovaSector/pull/3668)
- [Hemophage Balance Pass - Hemophages Suck Less Edition](https://github.com/NovaSector/NovaSector/pull/3706)
- [Snowglobe Station - A new icemoon station for nova!](https://github.com/NovaSector/NovaSector/pull/3207)
- [[MODULAR] Bodypart Layering Tweaks](https://github.com/NovaSector/NovaSector/pull/3780)
- [Update SMES Performance [NO GBP]](https://github.com/NovaSector/NovaSector/pull/3839)
- [[MIRROR] Allows humans with a robotic voicebox installed, MMIs, and posibrains to use silicon emotes, and simple/basic bots to beep [MDB IGNORE]](https://github.com/NovaSector/NovaSector/pull/3802)
- [[MODULAR] Adds armband crafting, that's it.](https://github.com/NovaSector/NovaSector/pull/3848)

## Reproduction:

This issue happens each time I open the loadout tab on the character preference window. It's happened every single time, and it gets spammed each time I hit a different catagory. Sometimes it's worse, spamming in the hundreds like it is for me right now. I'm not sure what's causing this at all, but it has something to do with the loadout menu. 

![image](https://github.com/user-attachments/assets/e0183328-c70d-4d37-92df-40121655ad88)

**Comment by FlufflesTheDog** [comment]
It's a known issue (so you won't get in trouble, don't worry) but it can be fixed by upgrading your byond

**Comment by Jolly-66** [comment]
This is a byond issue and can be remedied by updating byond to latest.
