### ISSUE TITLE
Synth emotes missing from side tabs

### ISSUE THREAD

**Issue by wivernshy** [NovaSector/NovaSector#3923]
Reporting client version: 515.1641

## Issue Summary
In the emotes/emotes+ tabs, synth emotes are missing. Can still use them as a synth with a robotic _lizard_ voicebox, they're just not showing up to the side.
Pics included just to show what I mean, they're not at the bottom if you scroll down either.
![image](https://github.com/user-attachments/assets/b1ceffb6-3c4a-4737-9b9f-99cffb9ceb24)
![image](https://github.com/user-attachments/assets/ae6d9cdf-23b5-43f3-80dc-f47128c5e795)

## Round ID:
[11290](https://scrubby.melonmesa.com/round/11290)

## Testmerges:
- [[TESTING ONLY] Debugging overlay cap being reached with taur parts](https://github.com/NovaSector/NovaSector/pull/2754)
- [Serenity Ambience DLC - Mushroom theme, several more ambience tracks for the mushroom caves and even some for the forest!](https://github.com/NovaSector/NovaSector/pull/3668)
- [Hemophage Balance Pass - Hemophages Suck Less Edition](https://github.com/NovaSector/NovaSector/pull/3706)
- [Snowglobe Station - A new icemoon station for nova!](https://github.com/NovaSector/NovaSector/pull/3207)
- [[MODULAR] Bodypart Layering Tweaks](https://github.com/NovaSector/NovaSector/pull/3780)
- [Update SMES Performance [NO GBP]](https://github.com/NovaSector/NovaSector/pull/3839)
- [[MIRROR] Allows humans with a robotic voicebox installed, MMIs, and posibrains to use silicon emotes, and simple/basic bots to beep [MDB IGNORE]](https://github.com/NovaSector/NovaSector/pull/3802)
- [[MODULAR] Adds armband crafting, that's it.](https://github.com/NovaSector/NovaSector/pull/3848)

**Comment by 00-Steven** [comment]
first guess:
https://github.com/NovaSector/NovaSector/blob/25887ec78016fe28095b0236379e1c02715ed81f/modular_nova/modules/emote_panel/code/emote_panel.dm#L235-L238
