### ISSUE TITLE
Scream broke

### ISSUE THREAD

**Issue by wivernshy** [NovaSector/NovaSector#3941]
Reporting client version: 515.1641

## Issue Summary
~~insert funny i have no mouth and i must scream joke~~
Scream emote stopped working, other audible emotes work just fine though.

## Round ID:
[11297](https://scrubby.melonmesa.com/round/11297)

## Testmerges:
- [[TESTING ONLY] Debugging overlay cap being reached with taur parts](https://github.com/NovaSector/NovaSector/pull/2754)
- [Serenity Ambience DLC - Mushroom theme, several more ambience tracks for the mushroom caves and even some for the forest!](https://github.com/NovaSector/NovaSector/pull/3668)
- [Hemophage Balance Pass - Hemophages Suck Less Edition](https://github.com/NovaSector/NovaSector/pull/3706)
- [Snowglobe Station - A new icemoon station for nova!](https://github.com/NovaSector/NovaSector/pull/3207)
- [[MODULAR] Bodypart Layering Tweaks](https://github.com/NovaSector/NovaSector/pull/3780)
- [Update SMES Performance [NO GBP]](https://github.com/NovaSector/NovaSector/pull/3839)

**Comment by GreytideSkye** [comment]
Reconfirmed on both a Podperson and a default human.

**Comment by RBasilisk** [comment]
I believe scream is not working across any species. I was also told, tested and found that *sad does not work either in the same way. Sad trombone.

**Comment by FlufflesTheDog** [comment]
Fixed by https://github.com/NovaSector/NovaSector/pull/3944
I assume *sad as well, but feel free to make a new report if not
