### ISSUE TITLE
Bitrunning Clown Planet uncompletable

### ISSUE THREAD

**Issue by JebSvS** [NovaSector/NovaSector#3950]
Reporting client version: 515.1637

## Issue Summary

Clown Planet bitrunning domain's objective door is unpowered, and no APC is around, neither are tools to open the door, making it unable to be completed

## Round ID:
[11299](https://scrubby.melonmesa.com/round/11299)

## Testmerges:
- [[TESTING ONLY] Debugging overlay cap being reached with taur parts](https://github.com/NovaSector/NovaSector/pull/2754)
- [Serenity Ambience DLC - Mushroom theme, several more ambience tracks for the mushroom caves and even some for the forest!](https://github.com/NovaSector/NovaSector/pull/3668)
- [Hemophage Balance Pass - Hemophages Suck Less Edition](https://github.com/NovaSector/NovaSector/pull/3706)
- [Snowglobe Station - A new icemoon station for nova!](https://github.com/NovaSector/NovaSector/pull/3207)
- [[MODULAR] Bodypart Layering Tweaks](https://github.com/NovaSector/NovaSector/pull/3780)
- [Update SMES Performance [NO GBP]](https://github.com/NovaSector/NovaSector/pull/3839)
- [Revert new smartfridge UI (#3916)](https://github.com/NovaSector/NovaSector/pull/3942)

## Reproduction:

Step 1: Select Clown Planet domain, enter
Step 2: Complete puzzle and arrive at door with the crate
Step 3: See that the door is unpowered

**Comment by RBasilisk** [comment]
I was looking for an issue report relevant to this after experiencing issues with it myself. I ended up shooting the bananium airlock open with a tech disk loaded.

Anyway, Island Brawl also starts partially depowered, the hotel particularly. Might be the same issue.

**Comment by 00-Steven** [comment]
This is likely to be a consequence of:
https://github.com/NovaSector/NovaSector/pull/3914
Mirrored from:
https://github.com/tgstation/tgstation/pull/85111

Specifically, it seems I believe it replaced the clown planet areas `/area/lavaland/surface/outdoors/virtual_domain`, which I believe doesn't have `requires_power = FALSE` like the base `/area/virtual_domain` it used to be, and thus it doesn't work.

**Comment by Sadboysuss** [comment]
Thank you for the report! This will be fixed by https://github.com/tgstation/tgstation/pull/85376
