### ISSUE TITLE
Bitrunning Breeze Bay uncompletable

### ISSUE THREAD

**Issue by JebSvS** [NovaSector/NovaSector#3951]
Reporting client version: 515.1637

## Issue Summary

Breeze Bay domain's fishing poles appear to be bugged upon usage, making it unable to be completed

## Round ID:
[11299](https://scrubby.melonmesa.com/round/11299)

## Testmerges:
- [[TESTING ONLY] Debugging overlay cap being reached with taur parts](https://github.com/NovaSector/NovaSector/pull/2754)
- [Serenity Ambience DLC - Mushroom theme, several more ambience tracks for the mushroom caves and even some for the forest!](https://github.com/NovaSector/NovaSector/pull/3668)
- [Hemophage Balance Pass - Hemophages Suck Less Edition](https://github.com/NovaSector/NovaSector/pull/3706)
- [Snowglobe Station - A new icemoon station for nova!](https://github.com/NovaSector/NovaSector/pull/3207)
- [[MODULAR] Bodypart Layering Tweaks](https://github.com/NovaSector/NovaSector/pull/3780)
- [Update SMES Performance [NO GBP]](https://github.com/NovaSector/NovaSector/pull/3839)
- [Revert new smartfridge UI (#3916)](https://github.com/NovaSector/NovaSector/pull/3942)

## Reproduction:

Step 1: Select Breeze Bay and enter
Step 2: Use fishing pole in water
Step 3: Observe that when the fishing pole is used, regardless of bait or not, the hover text 'already fishing' will appear. Alternatively, when using the fishing pole from one tile away, the hover text 'line snapped' will appear

**Comment by Sadboysuss** [comment]
Most certainly

**Comment by Sadboysuss** [comment]
since the fix was merged, marking this for cleanup, if it arises on Nova again - send a message
