### ISSUE TITLE
SolFed comms key conflicts with TG 'left-hand' comm shortcut

### ISSUE THREAD

**Issue by OrionTheFox** [NovaSector/NovaSector#3977]
## Issue Summary
TG has three comms keybinds that use specific held items to speak, rather than choosing a channel.
:r for Right Hand
:l (L) for Left Hand
:i for Adjacent Intercom

SolFed uses the :l (L) key, conflicting with using this key to speak into left-handed radios. 
You still CAN, but it attempts to speak over SolFed as well. Attempting to use this bind while having the encryption key and a radio in your left hand will likely cause issues, at the least confusion.
![image](https://github.com/user-attachments/assets/9964dac3-2856-43fd-8198-07afffd33d64)

## Round ID:
N/A

## Testmerges:
N/A

## Reproduction:
Hold something in your left hand
Type :l (L) to use the left hand item to speak
Observe that it attempts to speak over SolFed encryption

**Comment by SomeRandomOwl** [comment]
This has been like this for years technically, it just wasnt noticed before because we didnt update the tgui text box for the radio channel for it but that was something i added in myself to update the box for the coms like other coms do
