### ISSUE TITLE
Military Simulator bitrunning domain is not properly marked as Ghost Interactable

### ISSUE THREAD

**Issue by OrionTheFox** [NovaSector/NovaSector#4018]
Reporting client version: 515.1641

## Issue Summary
Island Brawl is an example that is marked correctly, including a description ending in `(Ghost Interaction)`

MilSim has neither a marking or description for this.
![image](https://github.com/user-attachments/assets/615bbad4-6efa-4df8-9e6f-5b7f72f1a93d)

## Round ID:
N/A

## Testmerges:
N/A

## Reproduction:
Open Bitrunner's `Quantum Console`
Under Hard difficulty, view the Ancient Military Simulator (may need to complete several earlier sims to progress to it)
Observe lack of Ghost Interaction marking and description

**Comment by Linkbro1** [comment]
hey! i just made a PR that fixes this! :D
