### ISSUE TITLE
Laser carbine + Root beer = MINIGUN

### ISSUE THREAD

**Issue by nikothedude** [NovaSector/NovaSector#406]
Reporting client version: 515.1621

## Issue Summary

Title. Drinking root beer and firing a laser carbine increases your rate of fire by significantly more than just 2x. At least, my brain tells me this.

## Round ID:
[10544](https://scrubby.melonmesa.com/round/10544)

## Testmerges:
- [Antag optin ](https://github.com/NovaSector/NovaSector/pull/121)
- [[TM ONLY] [EARLY MIRROR] Revert "Makes immerse use weakrefs", prioritizing some ref removal lines instead](https://github.com/NovaSector/NovaSector/pull/238)
- [[MODULAR] Removes Arbitrary Loadout Restrictions](https://github.com/NovaSector/NovaSector/pull/58)
- [[TM-ONLY] Testing chatmessage debug](https://github.com/NovaSector/NovaSector/pull/275)
- [[MIRROR] Replace natural beheading with cranial fissures (splitting your skull) (#80703)](https://github.com/NovaSector/NovaSector/pull/382)
- [The Thrill of the Hunt: Hemophage blood digestion changes](https://github.com/NovaSector/NovaSector/pull/93)

## Reproduction:

https://github.com/NovaSector/NovaSector/assets/59709059/c48b4fa1-57b3-4f3c-98d5-9a8e1ae310b6

**Comment by Namwty** [comment]
I mean root beer always was kinda strong, but with a downside that drinking it usually will cause downsides to point where your character would fall asleep.

But... I will say, I doubt that carbines were balanced around the fact... that root beer exists, cause well it's a niche item that I personally never seen anyone use.
As generally it seems it was balanced around single firing pistols/disablers?

So yeah, holy judging from the video, defo needs a tweak... considering this might be common issue if people realize that.

On other note, does root bear also effect other firearms, like FAST firing ballistics from cargo?
Doubt LMG or whatever shooting at that speed... would be less insane, if that is the case.

**Comment by jughu** [comment]
root beer was balanced around the fact crew didnt get a automatic lasergun which is just a little worse then a real lasergun when it comes to auctall firing power but in the end the damage output will stay the same
