### ISSUE TITLE
Echolocation model over-write

### ISSUE THREAD

**Issue by Krexah** [NovaSector/NovaSector#4094]
Reporting client version: 515.1642

## Issue Summary

Echolocation encounters a weird bug where everyone becomes the same model, despite not being said model, including ears and a wagging tail.
![Untitled](https://github.com/user-attachments/assets/394d851d-ec14-4821-be60-061f6df998ad)

## Round ID:
[11343](https://scrubby.melonmesa.com/round/11343)

## Testmerges:
- [[TESTING ONLY] Debugging overlay cap being reached with taur parts](https://github.com/NovaSector/NovaSector/pull/2754)
- [Snowglobe Station - A new icemoon station for nova!](https://github.com/NovaSector/NovaSector/pull/3207)
- [Revert new smartfridge UI (#3916)](https://github.com/NovaSector/NovaSector/pull/3942)
- [[MODULAR] Bodypart Layering Tweaks](https://github.com/NovaSector/NovaSector/pull/3780)
- [Refactor Synths away from /Robot/ limbs, Cybernetically augmented humanoids have alternative surgeries](https://github.com/NovaSector/NovaSector/pull/3970)
- [Fixes a hard del in character directory + enables live ref tracking (may cause some stutters)](https://github.com/NovaSector/NovaSector/pull/4067)

## Reproduction:

Not sure how you'd even replicate this. I only noticed it in detail when I entered the bar in Icebox, in which I can only assume one of the people using the model was in there and it over-wrote echolocation somehow. Something like this seems like it'd be so obscure that it's a rarity.

**Comment by Krexah** [comment]
A little note at the bottom I guess after some playing. Due to the person perfectly matching the outline when the walked past me,  the person that echolocation was pasting on everyone was Maxima Callera, the HoS.

**Comment by Sadboysuss** [comment]
https://github.com/tgstation/tgstation/pull/86604
