### ISSUE TITLE
Can't point at your gun while in hand

### ISSUE THREAD

**Issue by Sadboysuss** [NovaSector/NovaSector#4203]
Reporting client version: 515.1641

## Issue Summary
using default binds (shift+MMB) I was unable to point at my gun while it was in my hand. Presumably cause of the safety feature keybinds

## Round ID:
[11391](https://scrubby.melonmesa.com/round/11391)

## Testmerges:
- [[TESTING ONLY] Debugging overlay cap being reached with taur parts](https://github.com/NovaSector/NovaSector/pull/2754)
- [Snowglobe Station - A new icemoon station for nova!](https://github.com/NovaSector/NovaSector/pull/3207)
- [[MODULAR] Bodypart Layering Tweaks](https://github.com/NovaSector/NovaSector/pull/3780)
- [Fixes a hard del in character directory](https://github.com/NovaSector/NovaSector/pull/4067)
- [Revert "[MIRROR] Refactor Stat Panel styles and more TGUI-like appearance [MDB IGNORE]"](https://github.com/NovaSector/NovaSector/pull/4095)
- [Uh oh! The NT board of workplace safety is trying to blacklist the Akhter Co. Prybar!](https://github.com/NovaSector/NovaSector/pull/3635)
- [[MODULAR] Species Limbs in Augs+](https://github.com/NovaSector/NovaSector/pull/3738)
- ['Cybersun Training Sim' DM arena](https://github.com/NovaSector/NovaSector/pull/4183)
- [Adds a new Loadout Category](https://github.com/NovaSector/NovaSector/pull/4098)

**Comment by Hemlock32** [comment]
This is because pointing with a gun aims it at someone
You're attempting to aim at your gun with your gun.

Use your other hand to point at it, rather than pointing at it with the hand that is holding the gun
