### ISSUE TITLE
Tadpoles are unscoopable in Nova-exclusive maps

### ISSUE THREAD

**Issue by wivernshy** [NovaSector/NovaSector#4223]
Reporting client version: 515.1641

## Issue Summary
[Based on this PR](https://github.com/NovaSector/NovaSector/pull/4120)
Puddles in Nova's custom maps (or at least on Blueshift, haven't been able to test on Snow/Ouro/Serenity) don't give any tadpoles when you scoop from them.
Puddles I've tested so far are the Blueshift salon, and Blueshift botany.

## Round ID:
[11409](https://scrubby.melonmesa.com/round/11409)

## Testmerges:
- [[TESTING ONLY] Debugging overlay cap being reached with taur parts](https://github.com/NovaSector/NovaSector/pull/2754)
- [[MODULAR] Bodypart Layering Tweaks](https://github.com/NovaSector/NovaSector/pull/3780)
- [Fixes a hard del in character directory](https://github.com/NovaSector/NovaSector/pull/4067)
- [Revert "[MIRROR] Refactor Stat Panel styles and more TGUI-like appearance [MDB IGNORE]"](https://github.com/NovaSector/NovaSector/pull/4095)
- [Uh oh! The NT board of workplace safety is trying to blacklist the Akhter Co. Prybar!](https://github.com/NovaSector/NovaSector/pull/3635)
- [[MODULAR] Species Limbs in Augs+](https://github.com/NovaSector/NovaSector/pull/3738)
- [Adds a new Loadout Category](https://github.com/NovaSector/NovaSector/pull/4098)
- [Akula species (balance) change](https://github.com/NovaSector/NovaSector/pull/4190)
- [Adds a flat cardboard box](https://github.com/NovaSector/NovaSector/pull/4213)
- [Xenohybrids can do some xenomorph emotes](https://github.com/NovaSector/NovaSector/pull/4220)

## Reproduction:
Right click a puddle, the "scooping tadpoles" text will show but none will actually appear

**Comment by FlufflesTheDog** [comment]
https://github.com/tgstation/tgstation/pull/85691
