### ISSUE TITLE
Hairless hide makes metal noises when dropped

### ISSUE THREAD

**Issue by RealWinterFrost** [NovaSector/NovaSector#4241]
Reporting client version: 515.1642

## Issue Summary

When you drop the Hairless hide item it makes a metal sound when you drop it!

## Round ID:
[11434](https://scrubby.melonmesa.com/round/11434)

## Testmerges:
- [[TESTING ONLY] Debugging overlay cap being reached with taur parts](https://github.com/NovaSector/NovaSector/pull/2754)
- [[MODULAR] Bodypart Layering Tweaks](https://github.com/NovaSector/NovaSector/pull/3780)
- [Fixes a hard del in character directory](https://github.com/NovaSector/NovaSector/pull/4067)
- [Revert "[MIRROR] Refactor Stat Panel styles and more TGUI-like appearance [MDB IGNORE]"](https://github.com/NovaSector/NovaSector/pull/4095)
- [[MODULAR] Species Limbs in Augs+](https://github.com/NovaSector/NovaSector/pull/3738)
- [Akula species (balance) change](https://github.com/NovaSector/NovaSector/pull/4190)
- [Milsim Tweaks [after eight whole months of being abandoned]](https://github.com/NovaSector/NovaSector/pull/4225)
- [(Early Mirror) Fix inventory item interactions sometimes being blocked due to not counting as adjacent when not on a turf](https://github.com/NovaSector/NovaSector/pull/4229)

## Reproduction:

Read summary

**Comment by Sadboysuss** [comment]
`/obj/item/stack/sheet/hairlesshide`
Lol, Just null the sound or give it the skin sound introduced in https://github.com/tgstation/tgstation/pull/85254
