### ISSUE TITLE
Custom Species Name saves the same value over all slots

### ISSUE THREAD

**Issue by OrionTheFox** [NovaSector/NovaSector#4268]
Reporting client version: 515.1641

## Issue Summary
Setting the 'Custom Species Name' of a character slot will change it over all character slots

<details><summary>Slot 1</summary>

![image](https://github.com/user-attachments/assets/4d884598-49cb-4ea4-b5ce-181b85fc9c2e)

</details>
<details><summary>Slot 2, which was just edited</summary>

![image](https://github.com/user-attachments/assets/a6c05ed8-e0fa-486c-bfff-45f151fc178b)

</summary>
</details>
<details><summary>Slot 1 immediately after</summary>

![image](https://github.com/user-attachments/assets/9c276e9f-39a8-413d-8279-baf4d45840a2)

</details>

## Round ID:
[11465](https://scrubby.melonmesa.com/round/11465)

## Testmerges:
- [[TESTING ONLY] Debugging overlay cap being reached with taur parts](https://github.com/NovaSector/NovaSector/pull/2754)
- [[MODULAR] Bodypart Layering Tweaks](https://github.com/NovaSector/NovaSector/pull/3780)
- [Fixes a hard del in character directory](https://github.com/NovaSector/NovaSector/pull/4067)
- [Revert "[MIRROR] Refactor Stat Panel styles and more TGUI-like appearance [MDB IGNORE]"](https://github.com/NovaSector/NovaSector/pull/4095)
- [[MODULAR] Species Limbs in Augs+](https://github.com/NovaSector/NovaSector/pull/3738)
- [Milsim Tweaks [after eight whole months of being abandoned]](https://github.com/NovaSector/NovaSector/pull/4225)
- [Xenohybrids use the xenomorph blood decals](https://github.com/NovaSector/NovaSector/pull/4216)
- [[Early mirror] Preemptively fixes people permanently turning into potted plants](https://github.com/NovaSector/NovaSector/pull/4265)

## Reproduction:
Open character customization
Select any slot
Scroll down to Custom Species Name
Enter any value
Go to another slot
Enter any value into Custom Species Name again
Go back to the previous slot

---

Please help all my characters are turning into Felinids

**Comment by FlufflesTheDog** [comment]
I believe it's purely visual, there's several weird things like this, but it seems to go back to normal after re opening the menu

**Comment by Oxotnak** [comment]
It also happens to ringtone field
