### ISSUE TITLE
NIF programs are not persistent.

### ISSUE THREAD

**Issue by thudner24** [NovaSector/NovaSector#4291]
Reporting client version: 515.1641

## Issue Summary
Programs that are meant to carry over between rounds don't. (Reward points still do.)

## Round ID:
[11501](https://scrubby.melonmesa.com/round/11501) & 11502

## Testmerges:
- [[TESTING ONLY] Debugging overlay cap being reached with taur parts](https://github.com/NovaSector/NovaSector/pull/2754)
- [[MODULAR] Bodypart Layering Tweaks](https://github.com/NovaSector/NovaSector/pull/3780)
- [Fixes a hard del in character directory](https://github.com/NovaSector/NovaSector/pull/4067)
- [Revert "[MIRROR] Refactor Stat Panel styles and more TGUI-like appearance [MDB IGNORE]"](https://github.com/NovaSector/NovaSector/pull/4095)
- [[MODULAR] Species Limbs in Augs+](https://github.com/NovaSector/NovaSector/pull/3738)
- [Xenohybrids use the xenomorph blood decals](https://github.com/NovaSector/NovaSector/pull/4216)
- [[Early mirror] Preemptively fixes people permanently turning into potted plants](https://github.com/NovaSector/NovaSector/pull/4265)

## Reproduction:
Step 1: Buy programs that are noted as being carried between shifts
![image](https://github.com/user-attachments/assets/97c36a21-ce63-47aa-babe-8720707303f4)

Step 2: Wait a round (Just to be sure, I played it to completion)

Step 3: Programs are gone
![image](https://github.com/user-attachments/assets/7ed13af7-4a48-4a97-a717-15ba2e8f5b4f)

**Comment by FlufflesTheDog** [comment]
Did you configure the program to be saved? When you expand the info box for a program there should be a button near the bottom to toggle if you want to save it

**Comment by thudner24** [comment]
I didn't know that at the time, got it explained to me. It's kind of weird how it's hidden beneath the (in soulcatcher's case) lengthy flavor text and also off by default. But it also works as it should. Oops.
