### ISSUE TITLE
"Human AI" Divergency Oversights

### ISSUE THREAD

**Issue by RealWinterFrost** [NovaSector/NovaSector#4326]
### Client Version:

515.1642

### Issue Summary:

The Big Brother AI Divergency currently doesnt have the ability to revoke drone access nor has access to all languages. 

I am uncertain if the language specific was an oversight or intentional, but the revoke drone access should be built in.

### Round ID:

[11543](https://scrubby.melonmesa.com/round/11543)

### Test Merge Information:

- [[TESTING ONLY] Debugging overlay cap being reached with taur parts](https://github.com/NovaSector/NovaSector/pull/2754)
- [Revert "[MIRROR] Refactor Stat Panel styles and more TGUI-like appearance [MDB IGNORE]"](https://github.com/NovaSector/NovaSector/pull/4095)
- [Xenoarchaeology Artifacts](https://github.com/NovaSector/NovaSector/pull/4281)
- [Plutonian 'Sapper Gang' Mid-Round](https://github.com/NovaSector/NovaSector/pull/4069)
- [Balance reagent weapons](https://github.com/NovaSector/NovaSector/pull/4308)

### Reproduction Steps:

Play as "Big Brother" during the "Human AI" Divergency.

**Comment by Sadboysuss** [comment]
All of this is intended, there are drone controls in the robotics console, you can make a feature request upstream
