### ISSUE TITLE
Slime eating honey permanently reduces maximum health 

### ISSUE THREAD

**Issue by amidoingitright** [NovaSector/NovaSector#4329]
### Client Version:

515.1642

### Issue Summary:

Xenobio/roundstart slime eating honey permanently reduces maximum health 
instead of dealing toxin damage it just reduces the maximum health

### Round ID:

[11547](https://scrubby.melonmesa.com/round/11547)

### Test Merge Information:

- [[TESTING ONLY] Debugging overlay cap being reached with taur parts](https://github.com/NovaSector/NovaSector/pull/2754)
- [Revert "[MIRROR] Refactor Stat Panel styles and more TGUI-like appearance [MDB IGNORE]"](https://github.com/NovaSector/NovaSector/pull/4095)
- [Xenoarchaeology Artifacts](https://github.com/NovaSector/NovaSector/pull/4281)
- [Plutonian 'Sapper Gang' Mid-Round](https://github.com/NovaSector/NovaSector/pull/4069)
- [Balance reagent weapons](https://github.com/NovaSector/NovaSector/pull/4308)

### Reproduction Steps:

1. Be Xeno-slime/roundstart slime
2. Eat honey
3. Check health.

**Comment by Sadboysuss** [comment]
Xeno-slime as in jellyperson/stargazer/slimeperson or oozeling?

**Comment by amidoingitright** [comment]
> Xeno-slime as in jellyperson/stargazer/slimeperson or oozeling?

roundstart slime. 
the Xenobiological Slime Hybrid 
the race you set in the character editor

**Comment by Sadboysuss** [comment]
Please provide new reproduction steps or a video of the issue, otherwise this will be closed in 7 days.
