### ISSUE TITLE
Echolocation bug

### ISSUE THREAD

**Issue by Namwty** [NovaSector/NovaSector#4354]
### Client Version:

no idea something 514: or something the "Golden and everyone suggests one", but it's not UP TO DATE.

### Issue Summary:

[](url)Basically 2 known bugs, one is less serious, other is a lot more serious

Less serious - If you use fulton pack, everyone's outline is set as yours + fulton pack and.... they get pixel shifted, making even simple tasks as picking people up into fire carry impossible. But it's less serious, cause you just don't use fulton pack.

More serious - Anyone in vicinity, using holopad ( answering it or maybe AI using it ( not tested, but answering was )) breaks EVERY single outline of player into a player who was in holopad.

AKA if TESHARI calls you, and anyone in your room answers the holopad, congrats, you and everyone will have boxed teshari outline.

Now, this is most likely TG upstream bug, but no one will fix it on upstream, especially as they are busy with re-wallening stuff, and they don't have echolocation quirk, nor they have psykers often. ( A K A TG's Psykers is half cooked feature that no one cares about, same as promised "golems" etc, list is long )
TG upstream bug, it wll never be fixed in upstream, as they don't care about this feature enough. ( which is why this bug exists since it ever came up, and why we had like 6 PR different lag fixes )

Leaving it here as hopes that it get's fixed ( quirk is ours, so... maybe? ), but... these two bugs exist for about a year or so, so... who cares.

Normally:
![norm](https://github.com/user-attachments/assets/9acacc6b-1b4b-4a28-8d1a-0a6420971cf9)

Someone answered Holopad in vicinity:
Test 1 - Teshari called me in holopad and I've answered
![notnorm1](https://github.com/user-attachments/assets/93a0f8ac-f107-4e78-b3c7-5ea1d81872e8)

Test 2- Someone else, answered holopad, so now I see this standard cloaked human as everyone ( size varies )
![notnorm2](https://github.com/user-attachments/assets/4235974e-6c1e-4950-805d-4be614a313df)

### Round ID:

[11590](https://scrubby.melonmesa.com/round/11590), but honestly I don't think there are any logs that can assist with bug fixing.

### Test Merge Information:

Irelevant, most likely, fulton pack bug existed waaaaay long ago ( even echolocation PR maker said it's upstream bug )

The fulton pack issue is easy to avoid

But anyone using holopad, and you got a "difficulty tweak" *cloaker voice*

Again none of the bugs is completely gamebreaking, but I do not expect TG to fix them, due to differences in natures of server. So maybe someone will fix at least the holopad one here.

### Reproduction Steps:

Take a quirk "echolocation"

Be in cargo, who answers holopad from a prisoner

You and everyone has same outline as prisoner calling the holopad ( size depends on settings of each char, but outline is same ), no amounts of tg ui resets or rejoins or turning echoloation on and off will fix it.

You realize that unlike fulton old bug, you CANNOT AVOID holopad one, it just needs to happen within your vicinity.

**Comment by Sadboysuss** [comment]
Thank you for the report! Next time please make 2 separate issue reports if you have 2 issues to report

**Comment by Sadboysuss** [comment]
https://github.com/tgstation/tgstation/pull/86604
