### ISSUE TITLE
Synthetic arms disappear under jumpsuits from certain angles.

### ISSUE THREAD

**Issue by NewyearnewmeUwu** [NovaSector/NovaSector#4432]
### Client Version:

515.1637

### Issue Summary:

The E3N synth arms seem to disappear from the sides when you're wearing a jumpsuit. Critically, they reappear if you remove the jumpsuit. Noticed this in the ghost cafe, but this also does happen in the loadout preview. This happens with way more arms than just the E3N kind actually. This also only affects synthetic CHASSIS arms. The kind of arms you get from the Augmentations menu are not affected to my knowledge.

![image](https://github.com/user-attachments/assets/de1b3041-7a03-4c3c-9a1a-0f00239093c9)
![image](https://github.com/user-attachments/assets/ac95b1ea-fc59-4244-8010-773dce87e532)
![image](https://github.com/user-attachments/assets/3849e480-eda8-4785-9c76-d6d8a38d65c8)

### Test Merge Information:

[#2754: '[TESTING ONLY] Debugging overlay cap being reached with taur parts' by vinylspiders at commit 026b607c40](https://github.com/NovaSector/NovaSector/pull/2754)
[#4281: 'Xenoarchaeology Artifacts' by Microvolnovka19 at commit 86d39759f2](https://github.com/NovaSector/NovaSector/pull/4281)
[#4412: 'Expands the item and ability selection of bitrunning disks (ft. Finally Being Able To Treat Your Teammates)' by Stalkeros2 at commit 8ff1d06c7c](https://github.com/NovaSector/NovaSector/pull/4412)

### Reproduction Steps:

1. Make a synthetic humanoid.
2. Give them the E3N chassis.
3. No arms from the side view!

**Comment by NewyearnewmeUwu** [comment]
> Could be a corrupt icon cache issue, have you tried clearing that? It's in byond -> gear icon ->preferences->clear cache
> 
> ![image](https://private-user-images.githubusercontent.com/13398309/371555359-a9366715-b21e-4f5f-ab38-40f6ee649101.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0NTI1ODksIm5iZiI6MTcyNzQ1MjI4OSwicGF0aCI6Ii8xMzM5ODMwOS8zNzE1NTUzNTktYTkzNjY3MTUtYjIxZS00ZjVmLWFiMzgtNDBmNmVlNjQ5MTAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI3VDE1NTEyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3MTg2ZGFjOTI1ZjgxY2YwMjQwOTkzOGFlMzkxYzU2NmFiOGQyZWI1OWYxYTViMTM1NzhmMzFhZDM2NjY3MWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.SKdqEuTRhkySfHhy8N1oizRdhZTkBzF0QMNcIZqAtJo)
> 
> ![image](https://private-user-images.githubusercontent.com/13398309/371555404-673830a8-e441-4bba-ab27-a9ddca3404ad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0NTI1ODksIm5iZiI6MTcyNzQ1MjI4OSwicGF0aCI6Ii8xMzM5ODMwOS8zNzE1NTU0MDQtNjczODMwYTgtZTQ0MS00YmJhLWFiMjctYTlkZGNhMzQwNGFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI3VDE1NTEyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1NmU0YjM0OTkyNjhlNDgwNjAxYmYxZjhlNWFjMDA3MDEwOGJmM2Y2MjY2ODA3ZTQwYmQ4YjkwMTZjZTc5YjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.3wXQiWd25m0pjeQLlaB38onQiZJtnjECrR5Kw70wUfY)

I did this and it still happens.

**Comment by NewyearnewmeUwu** [comment]
I should note that the icons EXIST, they just aren't showing up for some reason ingame.

**Comment by FlufflesTheDog** [comment]
Fixed by #4441

For future reference, you can [link an issue](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests) to be closed when you make a PR if you say specifically `Fixes #4432` in the pr body
