### ISSUE TITLE
Portable SMES despawns when unscrewed.

### ISSUE THREAD

**Issue by Istasha528** [NovaSector/NovaSector#4486]
### Client Version:

515.1643

### Issue Summary:

After building a portable SMES and attempting to open the service panel, the SMES vanished.

### Round ID:

[11866](https://scrubby.melonmesa.com/round/11866)

### Test Merge Information:

- [[TESTING ONLY] Debugging overlay cap being reached with taur parts](https://github.com/NovaSector/NovaSector/pull/2754)
- [Fixes taur legs   augments not getting the correct footstep sounds from prefs](https://github.com/NovaSector/NovaSector/pull/4475)
- [Akula have been cured of the purple skin epidemic](https://github.com/NovaSector/NovaSector/pull/4480)
- [Removes the service bell ambience from Hilberts areas](https://github.com/NovaSector/NovaSector/pull/4483)
- [disables phasic ammo printing](https://github.com/NovaSector/NovaSector/pull/4484)

### Reproduction Steps:

1. Build Portable SMES
2. Attempt to use a screwdriver on the SMES.
3. ???
4. SMES gone.

**Comment by Sadboysuss** [comment]
Closed by https://github.com/tgstation/tgstation/pull/87250
