### ISSUE TITLE
Shady Market ruin active turfs

### ISSUE THREAD

**Issue by Thlumyn** [NovaSector/NovaSector#4509]
### Client Version:

515.1636

### Issue Summary:

Active turfs shady market ruin

### Round ID:

[11902](https://scrubby.melonmesa.com/round/11902)

### Test Merge Information:

- [[TESTING ONLY] Debugging overlay cap being reached with taur parts](https://github.com/NovaSector/NovaSector/pull/2754)
- [Space Ruin - Black Market Trader Balance pass](https://github.com/NovaSector/NovaSector/pull/4499)
- [Space Ruin - Cheese mitigation for NT Research Ship ](https://github.com/NovaSector/NovaSector/pull/4498)

### Reproduction Steps:

![image](https://github.com/user-attachments/assets/177edecc-04c7-4e85-a8d7-4cbf2fc7f28d)

**Comment by Zergspower** [comment]
fixed in the TM, it'll show in the next server update
