### ISSUE TITLE
Lobster lake under brig in Snowglobe leading to massive lag

### ISSUE THREAD

**Issue by Hardly3D** [NovaSector/NovaSector#4533]
### Client Version:

515.1642

### Issue Summary:

There's a lobster lake seemingly under brig in Snowglobe that seems to have crabs who are constantly reproducing(?) to the point it causes an awful amount of lag when looked at, someone in OOC said this was a thing that happens consistently.
Here's a screenshot I took before my GPU gave up
![dreamseeker_gfHyV9ZeIr](https://github.com/user-attachments/assets/25380858-b8af-40f7-b9c8-edc0ef4e12f6)

### Round ID:

11949

### Reproduction Steps:

1. Go (any way works) to the lobster lake under the brig in Snowglobe Station
2. Watch as FPS massively goes down.

**Comment by TheVekter** [comment]
![image](https://github.com/user-attachments/assets/fcbc937d-243e-40ff-bfce-e2ac4a604a95)

**Comment by Sadboysuss** [comment]
Closing in favor of https://github.com/NovaSector/NovaSector/issues/4576
