### ISSUE TITLE
Falling into chasm while bitrunning disregards your active host body and instant ghosts  you.

### ISSUE THREAD

**Issue by RealWinterFrost** [NovaSector/NovaSector#4544]
### Client Version:

515.1643

### Issue Summary:

The name

### Round ID:

[11974](https://scrubby.melonmesa.com/round/11974)

### Test Merge Information:

- [[TESTING ONLY] Debugging overlay cap being reached with taur parts](https://github.com/NovaSector/NovaSector/pull/2754)
- [Remove the Prybar from the RCF, Introduce the F.O.C.K. to hack doors, air alarms and APC's instead.](https://github.com/NovaSector/NovaSector/pull/4491)
- [Allows golem arms to dredge boulders from ore vents](https://github.com/NovaSector/NovaSector/pull/4511)
- [Assistant Bounties Modernization](https://github.com/NovaSector/NovaSector/pull/4518)
- [Add: Personal Holosign Projector](https://github.com/NovaSector/NovaSector/pull/4523)
- [retinal projector sprite adjustments: they clip through hair, ears and headwear less often](https://github.com/NovaSector/NovaSector/pull/4535)

### Reproduction Steps:

1. load in a session that has a chasm
2. Run into chasm during the session

**Comment by Sadboysuss** [comment]
Pr upstream to fix it is up
