### ISSUE TITLE
Snowglobe Disposals Mass Driver is just...

### ISSUE THREAD

**Issue by GreytideSkye** [NovaSector/NovaSector#4575]
### Client Version:

515.1642

### Issue Summary:

Tell me that's how a disposals mass driver should be aimed. Tell me that's how you personally get rid of trash.

![image](https://github.com/user-attachments/assets/42c69a2b-d47d-40ac-aa80-23c337cad717)

### Round ID:

[12037](https://scrubby.melonmesa.com/round/12037)

### Test Merge Information:

- [[TESTING ONLY] Debugging overlay cap being reached with taur parts](https://github.com/NovaSector/NovaSector/pull/2754)
- [Allows golem arms to dredge boulders from ore vents](https://github.com/NovaSector/NovaSector/pull/4511)
- [iskapass, october 2024](https://github.com/NovaSector/NovaSector/pull/4548)
- [Bitrunning prefloading](https://github.com/NovaSector/NovaSector/pull/4555)
- [Defaults all EMPs to being logged.](https://github.com/NovaSector/NovaSector/pull/4573)

### Reproduction Steps:

Be snowglobe.

**Comment by Syilumi** [comment]
laxative might help
