### ISSUE TITLE
Serenity Orbital Dock connected to Planetside station [Downstream]

### ISSUE THREAD

**Issue by Archemagus** [NovaSector/NovaSector#4656]
### Issue Summary:

1) This is from downstream, so issue may be already fixed.

2) I just hate every genius, who made system with all that RP stuff, to join discord server, not just game server, so I can't post memes there
3) So you'll get memes instead!
![image](https://github.com/user-attachments/assets/ab65d40e-d0cb-4323-9648-b227b4b3e5cd)
Context: Security in pursuit of AI sat, ended on Serenity Orbital Dock. And decided that they can shortcut through stations roof.
Best orbital drop ever.

4) Extras

![image](https://github.com/user-attachments/assets/59572368-9740-45f4-9fca-b1d9e89e8550)

https://github.com/user-attachments/assets/1f90d126-3795-467e-bfd4-ad74850e6eba

### Reproduction Steps:

1) Find a way to SerenityStation
2) Lift on orbit via shuttle
3) Observe station in floor-mounted porthole

**Comment by FlufflesTheDog** [comment]
Should be fixed as of https://github.com/NovaSector/NovaSector/pull/4636 (https://github.com/tgstation/tgstation/pull/87714)
