### ISSUE TITLE
Invisible Ears on Synthetic Humanoid

### ISSUE THREAD

**Issue by Floofies** [NovaSector/NovaSector#4657]
### Client Version:

515.1641

### Issue Summary:

When I spawn as a synthetic humanoid with Fox ears selected (not antenna, just Ears option), the ears sprite becomes invisible. The sprite appears as expected in the character preferences preview.

I took some  screenshots to show the issue:
![image](https://github.com/user-attachments/assets/fc84a15a-b0c1-4631-8ed1-42fdc9c407b1) ![image](https://github.com/user-attachments/assets/b50a0584-f897-4ba8-9ca5-decb4c7efb36)

### Round ID:

[12330](https://scrubby.melonmesa.com/round/12330)

### Test Merge Information:

Server revision compiled on: 2024-12-01T23:13:38+00:00
Master commit: [029152e48edc44afec270ed0af9b1db9ae261fc7]
Local commit: 8352e34a8e05ca8e71baff06f3146ef004ac4f4a

### Reproduction Steps:

1. Create a character with the "Synthetic Humanoid" species.
2. Enable the Ears checkbox.
3. Select "Fox" in Ears.
4. Spawn the character in-game (I used latejoin menu), the ears sprite should be invisible.

**Comment by Floofies** [comment]
I suspect that this may be caused by:
[#4641: 'Fixes ears getting sprites they shouldn't be getting when they're set to not having visuals' by GoldenAlpharex at commit aa920b763c](https://github.com/NovaSector/NovaSector/pull/4641)

**Comment by FlufflesTheDog** [comment]
Hopefully fixed by the later change in that linked PR, poke me if it happens again

**Comment by Floofies** [comment]
I found this from another player today. It seems the bug may still be an issue.

![Image](https://github.com/user-attachments/assets/107522b0-d95f-485c-b088-4a165d5e3b5a)
