### ISSUE TITLE
Nofruit failure to activate

### ISSUE THREAD

**Issue by Medziaga** [NovaSector/NovaSector#4684]
### Client Version:

515.1643

### Issue Summary:

When you place nofruit on the table instead of being able to pluck the leaf for it to change plants, you are unable to do anything but eat it. From what ive read on when it was added your meant to attack it with harm intent, so im guessing instead of working like it should, it only works with intents?

### Round ID:

[12402](https://scrubby.melonmesa.com/round/12402)

### Test Merge Information:

- [[TESTING ONLY] Debugging overlay cap being reached with taur parts](https://github.com/NovaSector/NovaSector/pull/2754)
- [Gun safety on deathmatch and bitdomains are off by default](https://github.com/NovaSector/NovaSector/pull/4616)
- [Restocking II, electric boogaloo (solfed pistols)](https://github.com/NovaSector/NovaSector/pull/4633)
- [New non lethal gun - P207   Fixes to the pepperball gun logistics](https://github.com/NovaSector/NovaSector/pull/4658)
- [Add Mannitol and Other Items to Imports](https://github.com/NovaSector/NovaSector/pull/4668)
- [Tinypaks, backpacks, but tiny [SLIGHTLY LESS MODULAR]](https://github.com/NovaSector/NovaSector/pull/4651)
- [[TM-ONLY] Market Crash: Cargo Contract](https://github.com/NovaSector/NovaSector/pull/4675)

### Reproduction Steps:

1. get nofruit.
2. set it down
3. fail to be able to do anything to the fruit no matter what or how you click.
4. pick up the fruit, be only able to eat it.

**Comment by FlufflesTheDog** [comment]
I don't see any code that suggests nofruit is supposed to have any special functionality, what is it you expect to be able to do/where did you hear that?

**Comment by Medziaga** [comment]
https://github.com/unitystation/unitystation/pull/8386 
This unity station thing, and the fact nofruit is a chowder reference so i thought it would do the reference.

**Comment by Medziaga** [comment]
nofruit wasn't even listed on the wiki so apologies if this was me not understanding and thinking it should of had something it didn't

**Comment by FlufflesTheDog** [comment]
Ahh, yeah that code isn't present here. No worries, better to ask than not. Nofruit here is just a niche thing you can get from xenoarch that has some mime-related chemicals, currently no functionality beyond that.
