### ISSUE TITLE
Borgs unable to whisper

### ISSUE THREAD

**Issue by wivernshy** [NovaSector/NovaSector#516]
Reporting client version: 514.1589

## Issue Summary
Cyborgs & AI shells can't whisper, and instead blare their secrets at max volume for everyone to hear.

## Round ID:
[10645](https://scrubby.melonmesa.com/round/10645)

## Testmerges:
- [Antag optin ](https://github.com/NovaSector/NovaSector/pull/121)
- [The Thrill of the Hunt: Hemophage blood digestion changes](https://github.com/NovaSector/NovaSector/pull/93)
- [[Semi-Modular]Ports over the old Food Perfs PR](https://github.com/NovaSector/NovaSector/pull/352)
- [[MODULAR] Adds a new reagent meant for cooling synthetic burns: Dinitrogen Plasmide](https://github.com/NovaSector/NovaSector/pull/445)
- [I'm here to chip this shit | Expands the selection of implants we have slightly with some funny silly new ones](https://github.com/NovaSector/NovaSector/pull/446)

## Reproduction:
1) be a borg
2) try to whisper your incredibly secret secrets (through a hotkey, in this case)
3) suffer
![image](https://github.com/NovaSector/NovaSector/assets/46330016/1d375f2e-9f62-4021-80e0-d76e47b9352d)

**Comment by Zergspower** [comment]
Whispering seems to affect everyone, it's not currently applying italics to chat
