### ISSUE TITLE
Meson layer fuckery, NorthStar Specific (OLD NAME: Unclickable Playing Area)

### ISSUE THREAD

**Issue by TripleShades** [NovaSector/NovaSector#650]
Reporting client version: 514.1589

## Issue Summary
Remaking from https://github.com/Skyrat-SS13/Skyrat-tg/issues/25437

## Round ID:
[10035](https://scrubby.melonmesa.com/round/10035)

## Testmerges:
- [Antag optin ](https://github.com/NovaSector/NovaSector/pull/121)
- [[Semi-Modular]Ports over the old Food Perfs PR](https://github.com/NovaSector/NovaSector/pull/352)
- [`Reagent_weapon` balance pass](https://github.com/NovaSector/NovaSector/pull/404)
- [[SEMI-MODULAR] [READY] Port Tarkon Redone: Nova Edition.](https://github.com/NovaSector/NovaSector/pull/358)
- [And look, the red just washes right out! | Changes a lot of blueshield equipment stuff and resprites their crew monitor](https://github.com/NovaSector/NovaSector/pull/372)
- [I See Clearly Now: customizable echolocation quirk](https://github.com/NovaSector/NovaSector/pull/525)
- [Revert "[MIRROR] ArcMining Pr Beta: Version 1.2"](https://github.com/NovaSector/NovaSector/pull/554)
- [Fundamental Equipment: roundstart loadout toolset implants](https://github.com/NovaSector/NovaSector/pull/453)
- [Billions must trauma team | Makes healthcare cheaper | DO NOT CROSS THE WARNING LINE | Freeman, take this medkit](https://github.com/NovaSector/NovaSector/pull/497)
- [Allows Spraypainting Synth Limbs | Also moves their ears](https://github.com/NovaSector/NovaSector/pull/637)

## Reproduction:
Map: Northstar
Unknown reproduction, listing effects and solution.

Screentips fail to show up when mousing over the playing field, and only show on the player GUI
Have to use shift + right click or alt + click a tile to interact with anything on a tile
Examining a tile, regardless of if something is on it, ignores everything except the tile, airlock, and if it has one, walls.

Changing to another z-level that was not the lowest floor of Northstar returned all functionality until returning to the lowest floor of Northstar.

Solution: Take off and put back on Mesons.

UPDATE:
Taking off and putting back on Mesons now has a chance to cause this:
![image](https://github.com/NovaSector/NovaSector/assets/6299921/7a273907-211d-41bc-b8d3-474308acd838)

Solution: Open the Game Preferences panel and it clears instantly.

**Comment by Floofies** [comment]
Hi is this still an issue?
Also, does this occur when you update to Byond version 515? Version 514 of Byond is no longer being used to develop Nova Sector.

**Comment by TripleShades** [comment]
I will update and attempt to report back within the year.

**Comment by TripleShades** [comment]
> Hi is this still an issue? Does this occur when you update to Byond version 515? Version 514 of Byond is no longer being used to develop Nova Sector.

Updating to latest beta resolved the issue, though there is still visual (harmless) glitching when transferring between station and lavaland with mesons on. I will close this as that's not really of much concern.
