### ISSUE TITLE
Gas masks aren't getting spray can protection 

### ISSUE THREAD

**Issue by MaSvedish** [NovaSector/NovaSector#658]
Reporting client version: 514.1589

## Issue Summary
For a while gas masks had spray can protection [target eyes, spray someone], it wouldn't blind you. This- at some point, has changed. Unsure if this is intentional change or a bug, but I'm reporting it regardless.

## Round ID:
[10039](https://scrubby.melonmesa.com/round/10039)

## Testmerges:
- [Antag optin ](https://github.com/NovaSector/NovaSector/pull/121)
- [[Semi-Modular]Ports over the old Food Perfs PR](https://github.com/NovaSector/NovaSector/pull/352)
- [`Reagent_weapon` balance pass](https://github.com/NovaSector/NovaSector/pull/404)
- [And look, the red just washes right out! | Changes a lot of blueshield equipment stuff and resprites their crew monitor](https://github.com/NovaSector/NovaSector/pull/372)
- [Revert "[MIRROR] ArcMining Pr Beta: Version 1.2"](https://github.com/NovaSector/NovaSector/pull/554)
- [Fundamental Equipment: roundstart loadout toolset implants](https://github.com/NovaSector/NovaSector/pull/453)
- [Billions must trauma team | Makes healthcare cheaper | DO NOT CROSS THE WARNING LINE | Freeman, take this medkit](https://github.com/NovaSector/NovaSector/pull/497)
- [Allows Spraypainting Synth Limbs | Also moves their ears](https://github.com/NovaSector/NovaSector/pull/637)

## Reproduction:
Spawn mask [ I tested the glass mask, mask/alt [the firecloset mask] and the default mask], 
Wear mask
apply spraycan
blind.

**Comment by Sadboysuss** [comment]
thank you for the report! This will be fixed by https://github.com/tgstation/tgstation/pull/85375
