### ISSUE TITLE
Sunglasses no longer remove photophobia mood debuff

### ISSUE THREAD

**Issue by rosextango** [NovaSector/NovaSector#688]
## Issue Summary

Sunglasses (and potentially other flash protecting items) no longer remove the debuff granted by photophobia.

## Testmerges:

[#121: 'Antag optin ' by nikothedude at commit 29cb901bc1](https://github.com/NovaSector/NovaSector/pull/121)
[#352: '[Semi-Modular]Ports over the old Food Perfs PR' by SomeRandomOwl at commit 71fc0938ab](https://github.com/NovaSector/NovaSector/pull/352)
[#372: 'And look, the red just washes right out! | Changes a lot of blueshield equipment stuff and resprites their crew monitor' by Paxilmaniac at commit 25482ff6e1](https://github.com/NovaSector/NovaSector/pull/372)
[#453: 'Fundamental Equipment: roundstart loadout toolset implants' by Ephemeralis at commit 1bf366a5b4](https://github.com/NovaSector/NovaSector/pull/453)
[#497: 'Billions must trauma team | Makes healthcare cheaper | DO NOT CROSS THE WARNING LINE | Freeman, take this medkit' by Paxilmaniac at commit 8a148dfdda](https://github.com/NovaSector/NovaSector/pull/497)
[#637: 'Allows Spraypainting Synth Limbs | Also moves their ears' by Nerev4r at commit d1aeb37c85](https://github.com/NovaSector/NovaSector/pull/637)
[#603: '[MODULAR] Down By The River: Telepathy improvements & telepathic quirk' by Ephemeralis at commit a48355315b](https://github.com/NovaSector/NovaSector/pull/603)
[#561: 'Its Microver | Deletes all of microfusion | Adds the coolest energy weapons you have seen ever' by Paxilmaniac at commit 0439609062](https://github.com/NovaSector/NovaSector/pull/561)
[#670: 'ARC Mining - Granite Fixes it Edition' by Zergspower at commit e08f578ea2](https://github.com/NovaSector/NovaSector/pull/670)
[#631: 'Adds a donator OOC icon, brings back donator OOC name colors' by GoldenAlpharex at commit 10920c0f42](https://github.com/NovaSector/NovaSector/pull/631)
[#549: '[MIRROR] Add: 2 Quirks Configs' by NovaBot13 at commit e2b7e936ac](https://github.com/NovaSector/NovaSector/pull/549)

## Reproduction:

Simply enter the game with a character who has photophobia. Get a pair of sunglasses. Wear them.

![image](https://github.com/NovaSector/NovaSector/assets/19510472/80c572ad-26a1-42e5-b279-1ee700cf205d)
![image](https://github.com/NovaSector/NovaSector/assets/19510472/a360670f-3047-4ab5-96e9-9efa4a876595)

And yes, they are real sunglasses. Taking them off and putting them on does not fix it.
![image](https://github.com/NovaSector/NovaSector/assets/19510472/5cfc8288-b09d-4364-a678-8f92fb1b3df9)

**Comment by Ephemeralis** [comment]
Did you take hypersensitive photophobia or are a moth? If so, that's -2 flash_protect, and sunglasses only add +1 - photophobia will continue applying the moodlet in bright areas until you have at least 0 flash_protect again.

**Comment by rosextango** [comment]
Ahhh, I must've missed that change. A weird change, but I understand. My bad!
