### ISSUE TITLE
Bluespace Technician MODsuit uses a broken module

### ISSUE THREAD

**Issue by OrionTheFox** [NovaSector/NovaSector#768]
## Issue Summary
![image](https://github.com/NovaSector/NovaSector/assets/76465278/98f832ca-6339-4281-902c-1bbff215d516)

## Round ID:
N/A - Private Server

## Testmerges:
None

## Reproduction:
Set outfit to Bluespace Technician
Open MOD interface
Find "MOD Module" - not a valid module, says yell at a coder
![image](https://github.com/NovaSector/NovaSector/assets/76465278/86c97ec8-35c4-4d11-bc86-71f5307e2e3c)

**Comment by MaSvedish** [comment]
Probably an oversight with the recent bluespace tech changes. This is the debug category item that doesnt have anything attached to it.
