### ISSUE TITLE
Recolorable Clothing Preferences Not Loading

### ISSUE THREAD

**Issue by xiangfei-chen** [NovaSector/NovaSector#799]
Reporting client version: 515.1630

Recolorable Clothing Preferences Not Loading
## Issue Summary
I've got several recolorable items in my loadout that I've customized, but when loading in for today's rounds, it won't load the loadout with my color preferences intact.

## Round ID:
[10102](https://scrubby.melonmesa.com/round/10102)

## Testmerges:
- [Antag optin ](https://github.com/NovaSector/NovaSector/pull/121)
- [[Semi-Modular]Ports over the old Food Prefs PR](https://github.com/NovaSector/NovaSector/pull/352)
- [And look, the red just washes right out! | Changes a lot of blueshield equipment stuff and resprites their crew monitor](https://github.com/NovaSector/NovaSector/pull/372)
- [Fundamental Equipment: roundstart loadout toolset implants](https://github.com/NovaSector/NovaSector/pull/453)
- [Billions must trauma team | Makes healthcare cheaper | DO NOT CROSS THE WARNING LINE | Freeman, take this medkit](https://github.com/NovaSector/NovaSector/pull/497)
- [[MODULAR] Down By The River: Telepathy improvements & telepathic quirk](https://github.com/NovaSector/NovaSector/pull/603)
- [Its Microver | Deletes all of microfusion | Adds the coolest energy weapons you have seen ever](https://github.com/NovaSector/NovaSector/pull/561)
- [ARC Mining - Granite Fixes it Edition](https://github.com/NovaSector/NovaSector/pull/670)
- [[MODULAR] Oh God The Zipper's Stuck: Entombed quirk granting unremovable roundstart MODsuit](https://github.com/NovaSector/NovaSector/pull/656)
- [Interdyne/DS2 Rising: Revengeance](https://github.com/NovaSector/NovaSector/pull/350)
- [Scene Girls Listening to Gloomy Bangers: Resprites Emo Long & All Gloomy Bangs variants](https://github.com/NovaSector/NovaSector/pull/697)
- [[MIRROR] Comprehensive cleanup of storage datum, replaces the weakrefs with just refs (because they were managed already)](https://github.com/NovaSector/NovaSector/pull/785)

## Reproduction:
Simply load into the round with your recolorable items recolored in the loadout menu. It will load without the colors you specified. Attempting to remove and then readd the items with the preferred colors before spawning in does not resolve the issue.

**Comment by xiangfei-chen** [comment]
![screenshot1](https://github.com/NovaSector/NovaSector/assets/77122122/64e55899-090e-4793-b031-44178d813c99)
![screenshot2](https://github.com/NovaSector/NovaSector/assets/77122122/f675c19b-2fb4-4070-860e-33aa4d28c8e9)

**Comment by xiangfei-chen** [comment]
Jorion reviewed this with me and this is the only PR that's recently touched greyscale items, and may potentially be a culprit: https://github.com/NovaSector/NovaSector/pull/791

**Comment by xiangfei-chen** [comment]
![screenshot3](https://github.com/NovaSector/NovaSector/assets/77122122/4b43341e-c40b-4876-8f23-a390790b1fa6)

Did some further testing and it appears that if you obtain recolorable clothing through a vendor in-round & recolor it before receiving it, it will be colored correctly.

**Comment by GreytideSkye** [comment]
Do they load the right colors when you join the game, or is it just with the Ghost Cafe spawner?

**Comment by TripleShades** [comment]
As someone who loaded into the round normally, my recolored items were also uncolored, but in the loadout still retained their proper color strings.

**Comment by kittysmooch** [comment]
in addition to the above the items aren't spawning with customs names

**Comment by xiangfei-chen** [comment]
> Do they load the (wrong) colors when you Join the Game, or is the issue just with the Ghost Cafe spawner?

They do. Both in round and the ghost cafe. The only way I can get the correct colors is from in-round vendors.

**Comment by FieryMorty** [comment]
I doubt that Entombed is the culprit because it appears to be random and for the past days Entombed has been TMed I've only had 1 random incident where specifically my colorable hood was uncolored, but my jeans were colored, and for all of the other rounds I had my hood the normal blue it should be.

**Comment by OrionTheFox** [comment]
Did a bit of poking around recent PRs; the one I mentioned earlier (#791) is unlikely to be involved now that I actually got to my PC to look at the code. That was a one-line change for UIs, and wouldn't have done anything to spawning.

However, I spawned in to the cafe in RoundID 10105 just now, and all GAGS loadout items seemed to appear as expected
![image](https://github.com/NovaSector/NovaSector/assets/76465278/52ee1ced-fdd3-456a-8c09-117196452d75)
(Default for the hood is white, and the cloak tan)
The difference: https://github.com/NovaSector/NovaSector/pull/785 is no longer Test-Merged; since it touches storage datums/refs, it might be what's upsetting our loadout system.

---
So, out of my knowledge area at this point, but one thing to ask to help narrow it down the rest of the way: what are your Loadout storage settings? Did your items get equipped directly without the color _(Delete/Move)_, or were they in your inventory and uncolored _(Place all in case)_?
![image](https://github.com/NovaSector/NovaSector/assets/76465278/c68666ef-7069-4473-b599-2e8ada8f9179)

**Comment by xiangfei-chen** [comment]
> Did a bit of poking around recent PRs; the one I mentioned earlier (#791) is unlikely to be involved now that I actually got to my PC to look at the code. That was a one-line change for UIs, and wouldn't have done anything to spawning.
> 
> However, I spawned in to the cafe in RoundID 10105 just now, and all GAGS loadout items seemed to appear as expected ![image](https://private-user-images.githubusercontent.com/76465278/302957045-52ee1ced-fdd3-456a-8c09-117196452d75.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczMzI3NTUsIm5iZiI6MTcwNzMzMjQ1NSwicGF0aCI6Ii83NjQ2NTI3OC8zMDI5NTcwNDUtNTJlZTFjZWQtZmRkMy00NTZhLThjMDktMTE3MTk2NDUyZDc1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA3VDE5MDA1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNjZmM3YmQ0M2U2NTBjNmRiMzY3ZWY3ZGEzMjc4MzEwYTRmZmM2NTgyYmRjNTg5ZGM0YjgxZDVkZjgxZTllOTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.paUNk3SmEVT2IHLm7SaimN57sLLt6ZcacEEUM9sma-k) (Default for the hood is white, and the cloak tan) The difference: #785 is no longer Test-Merged; since it touches storage datums/refs, it might be what's upsetting our loadout system.
> 
> So, out of my knowledge area at this point, but one thing to ask to help narrow it down the rest of the way: what are your Loadout storage settings? Did your items get equipped directly without the color _(Delete/Move)_, or were they in your inventory and uncolored _(Place all in case)_? ![image](https://private-user-images.githubusercontent.com/76465278/302958411-c68666ef-7069-4473-b599-2e8ada8f9179.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczMzI3NTUsIm5iZiI6MTcwNzMzMjQ1NSwicGF0aCI6Ii83NjQ2NTI3OC8zMDI5NTg0MTEtYzY4NjY2ZWYtNzA2OS00NDczLWI1OTktMmU4YWRhOGY5MTc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA3VDE5MDA1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg4OGVmMzZmZWUxYTcyY2RmMjFmNmFjMjI1ZWIxZGE3YTVhZjUwZjZhZjUzZWQ0YTJmNmIyNjk1NzU3YmRiMzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2r3KQeanE5ddkm4ltbdG_-fnNsp1-xyYs8V3rUNJ3U4)

I have my character currently set to Move job to backpack.

**Comment by TripleShades** [comment]
> So, out of my knowledge area at this point, but one thing to ask to help narrow it down the rest of the way: what are your Loadout storage settings? Did your items get equipped directly without the color _(Delete/Move)_, or were they in your inventory and uncolored _(Place all in case)_? ![image](https://private-user-images.githubusercontent.com/76465278/302958411-c68666ef-7069-4473-b599-2e8ada8f9179.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczNDY4MjQsIm5iZiI6MTcwNzM0NjUyNCwicGF0aCI6Ii83NjQ2NTI3OC8zMDI5NTg0MTEtYzY4NjY2ZWYtNzA2OS00NDczLWI1OTktMmU4YWRhOGY5MTc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA3VDIyNTUyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI0YmY1MWM0NWY4OTZhOTBiNjNjZmU0OTQxMDc0YmI0NGRhMjMzMDc5M2E0ZDg4NjI3Y2NlNGU3MmM4ODdhNDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AjurSpKRfl0916OBEy5Vqwri_SBy6zt0eUbrt4Jzr1w)

I have my characters set to Place all in Case.

**Comment by Floofies** [comment]
Hello! Is this still an issue?

**Comment by xiangfei-chen** [comment]
Nah. It's not been an issue anymore for a while.
