### ISSUE TITLE
Icebox Eyelight

### ISSUE THREAD

**Issue by MerlonFire21** [NovaSector/NovaSector#851]
Reporting client version: 514.1589

## Issue Summary

On Icebox, I found "eyelight" instead of a flashlight in a small janitor closet in the icebox POI "Abandoned Plasma Facility". Upon picking it up and putting it back down, it vanished. The description implies it might be for an implant or something: "This shouldn't exist outside of someone's head, how are you seeing this?". I figure this isn't intentional.

## Round ID:
[10115](https://scrubby.melonmesa.com/round/10115)

## Testmerges:
- [Antag optin ](https://github.com/NovaSector/NovaSector/pull/121)
- [[Semi-Modular]Ports over the old Food Prefs PR](https://github.com/NovaSector/NovaSector/pull/352)
- [And look, the red just washes right out! | Changes a lot of blueshield equipment stuff and resprites their crew monitor](https://github.com/NovaSector/NovaSector/pull/372)
- [Fundamental Equipment: roundstart loadout toolset implants](https://github.com/NovaSector/NovaSector/pull/453)
- [Billions must trauma team | Makes healthcare cheaper | DO NOT CROSS THE WARNING LINE | Freeman, take this medkit](https://github.com/NovaSector/NovaSector/pull/497)
- [[MODULAR] Down By The River: Telepathy improvements & telepathic quirk](https://github.com/NovaSector/NovaSector/pull/603)
- [Its Microver | Deletes all of microfusion | Adds the coolest energy weapons you have seen ever](https://github.com/NovaSector/NovaSector/pull/561)
- [ARC Mining - Granite Fixes it Edition](https://github.com/NovaSector/NovaSector/pull/670)
- [[MODULAR] Oh God The Zipper's Stuck: Entombed quirk granting unremovable roundstart MODsuit](https://github.com/NovaSector/NovaSector/pull/656)
- [Interdyne/DS2 Rising: Revengeance](https://github.com/NovaSector/NovaSector/pull/350)
- [Scene Girls Listening to Gloomy Bangers: Resprites Emo Long & All Gloomy Bangs variants](https://github.com/NovaSector/NovaSector/pull/697)
- [[MODULAR] Fixes synthetic organ manipulation surgery proccing pain](https://github.com/NovaSector/NovaSector/pull/772)

## Reproduction:

Enter the Abandoned Plasma Facility front doors "Interior Access". Walk down the hall, and into the door marked "Maintenance". Then, enter the door marked "Closet". On one of the 2 racks in the room, there'll be a pair of galoshes, and a flashlight called "Eyelight". Attempt to pick it up, then put it down, and they will vanish.

**Comment by Sadboysuss** [comment]
thanks for reporting! this will be closed by https://github.com/tgstation/tgstation/pull/85374
