### ISSUE TITLE
Spray can spam

### ISSUE THREAD

**Issue by TripleShades** [NovaSector/NovaSector#859]
Reporting client version: 514.1589

## Issue Summary
While having a closed spray can in your bag and laying down, hovering on and off of it spams your chat with "You can't do that right now!"

## Round ID:
[10116](https://scrubby.melonmesa.com/round/10116)

## Testmerges:
- [Antag optin ](https://github.com/NovaSector/NovaSector/pull/121)
- [[Semi-Modular]Ports over the old Food Prefs PR](https://github.com/NovaSector/NovaSector/pull/352)
- [And look, the red just washes right out! | Changes a lot of blueshield equipment stuff and resprites their crew monitor](https://github.com/NovaSector/NovaSector/pull/372)
- [Fundamental Equipment: roundstart loadout toolset implants](https://github.com/NovaSector/NovaSector/pull/453)
- [Billions must trauma team | Makes healthcare cheaper | DO NOT CROSS THE WARNING LINE | Freeman, take this medkit](https://github.com/NovaSector/NovaSector/pull/497)
- [[MODULAR] Down By The River: Telepathy improvements & telepathic quirk](https://github.com/NovaSector/NovaSector/pull/603)
- [Its Microver | Deletes all of microfusion | Adds the coolest energy weapons you have seen ever](https://github.com/NovaSector/NovaSector/pull/561)
- [ARC Mining - Granite Fixes it Edition](https://github.com/NovaSector/NovaSector/pull/670)
- [[MODULAR] Oh God The Zipper's Stuck: Entombed quirk granting unremovable roundstart MODsuit](https://github.com/NovaSector/NovaSector/pull/656)
- [Interdyne/DS2 Rising: Revengeance](https://github.com/NovaSector/NovaSector/pull/350)
- [Scene Girls Listening to Gloomy Bangers: Resprites Emo Long & All Gloomy Bangs variants](https://github.com/NovaSector/NovaSector/pull/697)
- [[MODULAR] Fixes synthetic organ manipulation surgery proccing pain](https://github.com/NovaSector/NovaSector/pull/772)

## Reproduction:
Put spray can in bag with cap on
Lay down
Run your mouse cursor over the spray can slot repeatedly

**Comment by Floofies** [comment]
See line 773 of [code\game\objects\items\crayons.dm](https://github.com/NovaSector/NovaSector/blob/master/code/game/objects/items/crayons.dm):

These functions create a contextual tooltip when the player hovers their mouse over the spraycan, and are likely the cause of the issue:

```dm
/obj/item/toy/crayon/spraycan/add_context(atom/source, list/context, obj/item/held_item, mob/living/user)
	. = ..()

	if(!user.can_perform_action(src, NEED_DEXTERITY|NEED_HANDS))
		return .

	if(has_cap)
		context[SCREENTIP_CONTEXT_ALT_LMB] = "Toggle cap"

	return CONTEXTUAL_SCREENTIP_SET

/obj/item/toy/crayon/spraycan/add_item_context(datum/source, list/context, atom/target, mob/living/user)
	. = ..()

	if(!user.can_perform_action(src, NEED_DEXTERITY|NEED_HANDS))
		return .

	context[SCREENTIP_CONTEXT_LMB] = "Paint"
	context[SCREENTIP_CONTEXT_RMB] = "Copy color"

	return CONTEXTUAL_SCREENTIP_SET
```

Another problem I see is that spraycan somehow has two `Initialize` functions declared, one on line 762 and one on line 818. While probably not relevant to the issue, it is a notable oversight.

**Comment by TripleShades** [comment]
Updating with: This actually can trigger from a distance, as well, except you get "You are too far away!" spammed instead.

**Comment by TripleShades** [comment]
Fixed by https://github.com/NovaSector/NovaSector/pull/2203
