### ISSUE TITLE
ORM Redemption Issues

### ISSUE THREAD

**Issue by DireWaff** [NovaSector/NovaSector#901]
## Issue Summary
While playing as the golem ghost role on icebox, there is an issue with the ore bags/satchels things. Or... Ore stacks in general? It's hard to know the extent of the issue and test this stuff, I apologize. But the glitch goes as follows: Stacks of ore will randomly not be accepted by the ORM. I've found a sort of fix for this, by pulling one-less than what the original stack had into a new one, and it will sometimes be taken by the ORM.

## Round ID:
[10050](https://scrubby.melonmesa.com/round/10050), but been a while since I've played.

## Reproduction:
I just went mining with the basic ore bag on ice box, got some normal ores with the head golem's special resonator, and the bag will scoop up ore as normal. However, when trying to put stacks into the ORM, some of the stacks just will not be accepted.

**Comment by Floofies** [comment]
Hi! Is this still an issue? If so how often does it occur?

**Comment by Sadboysuss** [comment]
Doesn't seem to be an issue anymore, comment here if you still see it happening.
This is marked for cleanup and will be auto-closed in 7 days
