### ISSUE TITLE
'Syndicate Sleeper Agent Borked'

### ISSUE THREAD

**Issue by RatFromTheJungle** [NovaSector/NovaSector#920]
## Issue Summary
The midround roll, 'syndicate sleeper agent' never picks someone to roll it, or even tries too, when bussed or not

## Round ID:

[10129](https://scrubby.melonmesa.com/round/10129)
## Testmerges:

#352 
#453
#656
#350 
#752
#660 
#669
## Reproduction:

boot up in round, try to roll event, no work

**Comment by Floofies** [comment]
Does this happen on TG at all?
